api/package.json
api/src/modules/config/app-config.service.ts
api/src/modules/import/services/entity.preprocessor.ts
api/src/modules/model/base-data.entity.ts
api/src/modules/model/base-data.repository.ts
api/src/modules/model/entities/carbon-input.entity.ts
api/src/modules/model/entities/cost-input.entity.ts
api/tsconfig.json

This pull request introduces several changes to the `api` module, focusing on adding new entities, updating existing data models, and refining data processing. The most important changes include adding new entities for cost and carbon inputs, updating the `BaseData` entity to include new fields, and refining the data insertion and update logic in the repository.
* [`api/src/modules/model/entities/carbon-input.entity.ts`](diffhunk://#diff-6675d5e118a24bc95cc2490b8f4fcc085e5b59b055d6dfa4c315e61c1c689787R1-R47): Added a new `CarbonInputEntity` to represent carbon input data.
* [`api/src/modules/model/entities/cost-input.entity.ts`](diffhunk://#diff-587894a816349bdbc7d36f5523a9f37d08af8d08478682d9913de9a5d86d6491R1-R47): Added a new `CostInput` entity to represent cost input data.
* …

chore data model first verions

---

client/src/containers/profile/account-details/schema.ts
shared/entities/users/roles.enum.ts
shared/entities/users/user.entity.ts

This pull request includes changes to the user role management in the project. The main focus is on removing the `GENERAL_USER` role and updating the default role for users.
Changes to user roles:
* [`client/src/containers/profile/account-details/schema.ts`](diffhunk://#diff-b5815fada5d0499f6927eddd3f1da1f6a57a3893227621f367ede6383d8d1a50L7-R7): Removed the `GENERAL_USER` role from the `role` enumeration in the `accountDetailsSchema`.
* [`shared/entities/users/roles.enum.ts`](diffhunk://#diff-3bf12782ae865ed75c3d57809d95ac89c6f204763a7c65fdf039e69e65af80deL2-R3): Removed the `GENERAL_USER` role from the `ROLES` enum.
* [`shared/entities/users/user.entity.ts`](diffhunk://#diff-29505a955d562ff7946ea8d0a7e7ecc5257c5e64785b05ccb28303339c7b8bcdL37-R37): Updated the default user role from …

remove general user role

---

client/package.json
pnpm-lock.yaml

This pull request primarily updates dependencies in the `client/package.json` and `pnpm-lock.yaml` files to ensure compatibility and improve security. Below are the most important changes:
* Updated `eslint-config-next` from `14.2.8` to `14.2.16` in `client/package.json` and `pnpm-lock.yaml` to ensure compatibility with the latest ESLint and TypeScript versions. [[1]](diffhunk://#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fL53-R53) [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR12-R32) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL368-R390) [[4]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbL4540-R4501) …

[chore] bumps eslint-config-next@14.2.16

---

api/src/modules/auth/authentication.service.ts
api/test/integration/auth/create-user.spec.ts

This pull request introduces changes to the `AuthenticationService` and related tests to support user roles during user creation. The most important changes include updating the user creation logic to handle roles and adding corresponding test cases to ensure the functionality works as expected.
* Updated `createUser` method to include `role` in the user creation process. (`api/src/modules/auth/authentication.service.ts`, [[1]](diffhunk://#diff-d5531e6f14eff2e79ca54062b2a8760e45de6ae82f192f8eb4034d48f014e652L60-R60) [[2]](diffhunk://#diff-d5531e6f14eff2e79ca54062b2a8760e45de6ae82f192f8eb4034d48f014e652R73)
* Added `jest.clearAllMocks()` to reset mocks before each test run. (`api/test/integration/auth/create-user.spec.ts`, [api/test/integration/auth/create-user.spec.tsR21](diffhunk://#diff- …

fix missing role in create user

---

api/src/modules/calculations/calculation.engine.ts
api/src/modules/custom-projects/custom-projects.controller.ts
api/src/modules/custom-projects/custom-projects.service.ts
api/test/integration/custom-projects/custom-projects-setup.spec.ts
shared/contracts/custom-projects.contract.ts
shared/dtos/custom-projects/default-cost-inputs.dto.ts
shared/dtos/custom-projects/get-default-cost-inputs.dto.ts
shared/schemas/custom-projects/get-cost-inputs.schema.ts

This pull request introduces several updates to the custom projects module, mainly focusing on adding functionality to retrieve default cost inputs. The changes include new methods, DTOs, and tests to support this feature.
* [`api/src/modules/calculations/calculation.engine.ts`](diffhunk://#diff-3fadd62658222f544e8089accf3574de621be7416f7d97e20ca45c7d3b127e37L56-R92): Added a method `getDefaultCostInputs` to fetch default cost inputs based on country, activity, and ecosystem.
* [`api/src/modules/custom-projects/custom-projects.controller.ts`](diffhunk://#diff-cc9c8bff38622ff15dd4ba62ed57da7aa1af212d09902ea07100a2182a45147eR45-R55): Introduced a new endpoint `getCostInputs` to handle requests for default cost inputs.
* [`api/src/modules/custom-projects/custom-projects.service.ts`](diffhunk: …

basic endpoint to get default cost inputs for custom project creation

---

client/src/components/ui/slider.tsx
client/src/containers/projects/filters/index.tsx
client/src/lib/format.tsx

This pull request introduces several enhancements to the `slider` component and adds a utility function for number formatting. The main changes include adding tooltips to the slider component, allowing custom formatting of slider values, and updating the project filters to use the new formatting function.
Enhancements to `slider` component:
* [`client/src/components/ui/slider.tsx`](diffhunk://#diff-08230162d8629480f37e9758a0ed105d95a0db6ac9a7a39a0e62220ba1c82ae6R9-R14): Added tooltips to display slider values and introduced a `format` prop to allow custom formatting of slider values. [[1]](diffhunk://#diff-08230162d8629480f37e9758a0ed105d95a0db6ac9a7a39a0e62220ba1c82ae6R9-R14) [[2]](diffhunk://#diff-08230162d8629480f37e9758a0ed105d95a0db6ac9a7a39a0e62220ba1c82ae6L51-R101)
Updates to …

adds tooltip to thumb slider

---

client/src/containers/overview/filters/index.tsx
client/src/containers/overview/header/parameters/index.tsx

This pull request includes several changes to the `client/src/containers/overview` directory, focusing on improving the handling of cost range filters in the `ProjectsFilters` and `ParametersProjects` components. Key changes include the removal of an unnecessary `useEffect` hook and the addition of logic to reset cost ranges when a selector is changed.
Changes to `ProjectsFilters` component:
* Removed the `useEffect` hook that reset cost ranges on component mount, as it was redundant.
Changes to `ParametersProjects` component:
* Added import for `INITIAL_COST_RANGE` to ensure cost ranges are properly reset.
* Updated the `setFilters` function to reset the `costRange` when the `costRangeSelector` parameter is changed.

[N/A] fixes sync of cost value with query params

---

client/src/app/auth/api/[...nextauth]/config.ts

- Override the default cookie name settings
Better dev experience when switching nextjs projects on your local machine.

Changed cookie name

---

api/src/modules/import/dtos/excel-projects.dto.ts
api/src/modules/import/services/entity.preprocessor.ts

**IMPORTANT**: There has been several changes in the source datasheet:
We are missing price type, which is a filtering value and it is required: I have inserted values artificially in my local DB to keep working
'`$/tCO2e` has been renamed to cost_per_tco2e
`$/tCO2e (NPV)` is missing now
This pull request includes changes to the `ExcelProjects` type and the `EntityPreprocessor` class to correct property names and handle missing columns in the Excel sheet.
Changes to `ExcelProjects` type:
* Corrected property names from `aAbatement_potential` to `abatement_potential` and `total_cost_NPV` to `total_cost_npv`.
* Added a TODO comment for the missing column `$/tCO2e (NPV)`.
* Renamed property `/tCO2e'` to `cost_per_tco2e`.
Changes to `EntityPreprocessor` class:
* Updated property names to …

temporal workaround to missing column data

---

admin/datasource.ts
admin/index.ts
shared/entities/custom-project.entity.ts

This pull request includes several changes to the `admin` and `shared/entities` files to improve the handling of custom projects and fix formatting issues. The most important changes include adding the `CustomProject` entity to the admin data source, updating the `CustomProject` entity class, and fixing formatting issues in the `admin/index.ts` file.
* [`admin/datasource.ts`](diffhunk://#diff-3535e4a53b9a703bd9500357217ef5c229f486d89ff9c97b2d2e223f79914aceR35-R40): Added the `CustomProject` entity to the `ADMINJS_ENTITIES` array to include it in the admin data source.
* [`shared/entities/custom-project.entity.ts`](diffhunk://#diff-e5e80ffb3610ba2df6a4c8684839aecc64c3037284b9f022ce1529add42085e1L15-R24): Updated the `CustomProject` entity class by adding a type to the `projectName` column …

bugfix/add custom-projects to BO datasource, type projectName column

---

client/src/components/ui/dialog.tsx
client/src/components/ui/info-button.tsx
client/src/constants/tooltip.tsx
client/src/containers/overview/table/toolbar/index.tsx

- Implement Scorecard Tab Content with Dynamic Descriptions
- Improves code maintainability by centralizing descriptions in the tooltip.tsx file.

Added tooltip constant file to store text / tsx content for tooltip across the app.

---

client/src/containers/overview/project-details/index.tsx

Removed **Compare with a different project** button from both Scorecard ratings and Cost estimates Card sections

fix: hide compare feat from project detail

---

backoffice/providers/auth.provider.ts

This pull request includes a small but important change to the `backoffice/providers/auth.provider.ts` file. The change ensures that the `__Secure-next-auth.session-token` cookie is properly cleared when logging out.
Changes to cookie handling:
* [`backoffice/providers/auth.provider.ts`](diffhunk://#diff-5e6b825379c79f89b1b8babd0ce0abd59ad840e1376762d6bc8a99877904a265R41): Added the `__Secure-next-auth.session-token` cookie to the list of cookies being cleared during logout.

bug(backoffice): The logout handler should also remove the next-auth.session-token not only in dev but in target environments

---

.github/workflows/deploy.yml

This pull request includes changes to the `.github/workflows/deploy.yml` file to update the dependencies for various jobs. The most important changes involve modifying the `needs` dependencies from `set_environment` to `set_environment_name` for the `build_client`, `build_api`, and `build_backoffice` jobs.
Updates to job dependencies:
* Changed `needs` dependency from `set_environment` to `set_environment_name` for the `build_client` job. (`.github/workflows/deploy.yml`, [.github/workflows/deploy.ymlL58-R58](diffhunk://#diff-28802fbf11c83a2eee09623fb192785e7ca92a3f40602a517c011b947a1822d3L58-R58))
* Changed `needs` dependency from `set_environment` to `set_environment_name` for the `build_api` job. (`.github/workflows/deploy.yml`, …

chore(cd): Adjust deployment rules for target environments (2)

---

api/src/modules/custom-projects/custom-projects.service.ts
api/src/modules/projects/projects.controller.ts
api/src/modules/projects/projects.service.ts
api/test/integration/custom-projects/custom-projects-read.spec.ts
api/test/integration/projects/projects.spec.ts
shared/contracts/custom-projects.contract.ts
shared/contracts/projects.contract.ts
shared/dtos/projects/projects.dto.ts

This pull request introduces several enhancements to the `CustomProjectsService` and `ProjectsService` in the API, including new filtering capabilities and the ability to retrieve maximum values for certain project attributes. Additionally, it updates related contracts and tests to support these changes.
* Added a new type `CustomProjectFetchSpecificacion` and schema `customProjecsQuerySchema` to support filtering by `partialProjectName` in `CustomProjectsService`. [[1]](diffhunk://#diff-a450b42f83aa743e906c235e1dbcc649854328c6951985e9bcaf6a40b6029eacL23-R28) [[2]](diffhunk://#diff-a450b42f83aa743e906c235e1dbcc649854328c6951985e9bcaf6a40b6029eacL124-R129)
* Implemented filtering logic in `extendFindAllQuery` method to allow querying by partial project name.
* Introduced …

Feat search projects with maximums

---

client/src/containers/nav/index.tsx

This pull request includes changes to the navigation component in the `client/src/containers/nav/index.tsx` file to enhance the navigation menu based on user authentication and role. The most important changes include adding role-based and authentication-based filtering for navigation items, and refactoring the code to use `useMemo` for performance optimization.
Enhancements to navigation menu:
* Imported `useMemo` and `ROLES` to facilitate memoization and role checking.
* Added `isAuth` and `isAdmin` properties to navigation items for conditional rendering based on user status.
* Updated `MainNav` to include `data` from `useSession` and determine if the user is an admin.
* Used `useMemo` to filter `navItems` based on user authentication and admin status, improving performance by …

[TBCCT-186] updates main nav according to authentication

---

client/src/components/ui/slider.tsx

This pull request includes changes to the `RangeSlider` component in the `client/src/components/ui/slider.tsx` file to enhance its functionality by adding drag state management for the slider thumbs. The most important changes include importing the `useState` hook, adding state management for dragging, and updating the `Tooltip` component to reflect the dragging state.
Enhancements to `RangeSlider` component:
* [`client/src/components/ui/slider.tsx`](diffhunk://#diff-08230162d8629480f37e9758a0ed105d95a0db6ac9a7a39a0e62220ba1c82ae6R4): Imported the `useState` hook from React.
* [`client/src/components/ui/slider.tsx`](diffhunk://#diff-08230162d8629480f37e9758a0ed105d95a0db6ac9a7a39a0e62220ba1c82ae6R62-R65): Added `isDragging` state to manage the dragging state of the left and right slider …

[TBCCT-201] slider: displays current value while dragging the thumb

---

client/src/containers/overview/project-details/index.tsx
client/src/hooks/use-feature-flags.ts

This pull request introduces feature flag functionality to conditionally render the project comparison section in the `ProjectDetails` component. The key changes include importing necessary dependencies, defining a new feature flag, and updating the component to use this feature flag.
Feature flag implementation:
* [`client/src/hooks/use-feature-flags.ts`](diffhunk://#diff-9bef22236b2667b970b8513c8c38b633dd5758f86fc8655b4795059cc6bc71b5R4): Added a new feature flag `project-comparison` to the `FEATURE_FLAGS` object.
* [`client/src/containers/overview/project-details/index.tsx`](diffhunk://#diff-7a7251e1c75b096ea0ca72f525b181411c23b9099fd0225317d6b51ddbafdeb9R16-R17): Imported the `useFeatureFlags` hook and utilized it to conditionally render the project comparison section based on the …

[N/A] adds "projects-comparison" feature flag

---

client/src/containers/my-projects/index.tsx
client/src/containers/overview/table/view/key-costs/index.tsx
client/src/containers/overview/table/view/overview/index.tsx
client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
client/src/hooks/use-table-pagination-reset.ts

- Create reusable hook to reset pagination on search
- Implement hook across all table views (Overview, KeyCosts, ScorecardPrioritization)
- Ensure users start from page 1 when performing new searches
[TBCCT-205](https://vizzuality.atlassian.net/browse/TBCCT-205)
[TBCCT-205]: https://vizzuality.atlassian.net/browse/TBCCT-205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added useTablePaginationReset hook for consistent search behavior

---

client/src/middleware.ts

This pull request includes a small change to the `client/src/middleware.ts` file. The change updates the `PRIVATE_PAGES` regex to include the `/my-projects` path, ensuring that the middleware applies to both `/profile` and `/my-projects`.
* [`client/src/middleware.ts`](diffhunk://#diff-e9afcce1307f539338e73b9d862ceaa5bf8be0ab3d07f702f41e024342ae748cL5-R5): Updated `PRIVATE_PAGES` regex to include `/my-projects`.

[N/A] adds /my-projects page to auth middleware

---

client/src/containers/overview/table/view/key-costs/index.tsx
client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
shared/contracts/projects.contract.ts

This pull request includes several updates to improve the filtering and sorting functionality in the `KeyCostsTable` and `ScoredCardPrioritizationTable` components, as well as updates to the project contracts.
* [`client/src/containers/overview/table/view/key-costs/index.tsx`](diffhunk://#diff-dfdd1ccddd5007c43db2bf0a58e1445909c68f9c2ca6638d963af5e11a45e3a1L69-L73): Removed commented-out code related to sorting and fields in the query parameters.
* [`client/src/containers/overview/table/view/scorecard-prioritization/index.tsx`](diffhunk://#diff-bfda56ea32fe24a32f96278c9094684ecab2b166f83dd583aeb295e0dd7bf072L73-R86): Added additional filters (`costRange`, `abatementPotentialRange`, `costRangeSelector`, and `partialProjectName`) and sorting logic to the query parameters.
* …

[N/A] adds query params to /scorecard endpoint

---

client/src/components/ui/score-card.tsx
client/src/components/ui/search.tsx
client/src/components/ui/sidebar.tsx
client/src/containers/my-projects/columns.tsx
client/src/containers/my-projects/index.tsx
client/src/containers/nav/index.tsx
client/src/containers/overview/header/parameters/index.tsx
client/src/containers/overview/map/index.tsx
client/src/containers/overview/project-details/index.tsx
client/src/containers/overview/table/toolbar/index.tsx
client/src/containers/overview/table/view/overview/index.tsx
client/src/hooks/use-feature-flags.ts
client/tailwind.config.ts

- Improve search component layout and accessibility
- Add map resize handling with sidebar state
- Enhance table styling and interactions
- Implement feature flags documentation
- Add methodology page navigation
[FE  - Design review](https://vizzuality.atlassian.net/browse/TBCCT-189)

Enhance UI components and navigation

---

client/src/containers/overview/table/view/overview/columns.tsx

- Added reusable `HeaderText` and `CellText` components for consistent text styling across table
- Standardized font sizes and weights using these components
- Updated column headers with more precise labels (e.g., added "tCO2e/yr" unit)
- Enhanced visual distinction between CapEx and OpEx in Total Cost column using color coding
- Replaced generic `<span>` and `<p>` elements with semantic components
- All table headers now use consistent text-xs font size and normal font weight
- All cell values now use consistent text-sm font size and normal font weight
- CapEx (blue-500) and OpEx (blue-200) are now visually distinguished in the Total Cost column header
- Added proper spacing between CapEx and OpEx labels using `&nbsp;`
- Created two new components:
- `HeaderText`: Standardizes header …

Refactor: standardize table header and cell text styling

---

client/src/app/(overview)/store.ts
client/src/containers/overview/project-details/index.tsx
client/src/containers/overview/project-details/parameters/index.tsx
client/src/lib/query-keys.ts

- Removed projectSizeFilter and priceType from project details filters
- Simplified the project details API query by removing unused filter parameters
- Updated types and interfaces to reflect the reduced filter set
- Removed unused imports from project entities
- Streamlined the parameters component to only show cost selector options
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-218)

[FE]: Remove "project size" and "carbon pricing type" from project overview detail sidebar

---

client/src/containers/my-projects/columns.tsx

This PR refactors the delete functionality in the `ActionsDropdown` component to support the deletion of multiple projects at once. Key changes include:
- Updated the `deleteCustomProject` function to `deleteCustomProjects`, allowing it to accept an array of IDs.
- Modified the `handleDelete` function to collect selected project IDs and call the updated deletion function.
- Improved success and failure messages to accurately reflect the number of projects deleted or failed to delete.
- Added query invalidation to refresh the project list after successful deletions.

Refactor delete functionality in ActionsDropdown component

---

client/src/app/(overview)/url-store.ts
client/src/containers/overview/filters/index.tsx
client/src/containers/overview/header/parameters/index.tsx

This pull request introduces enhancements to the project size filter functionality. The `projectSizeFilter` has been modified to allow multiple selections by changing its type from a single enum value to an array. The initial state is now set to an empty array. 
Additionally, the `ProjectsFilters` component has been updated to include checkboxes for each project size, enabling users to select multiple sizes. The project size parameter definition has been removed from the `PROJECT_PARAMETERS` as it is now handled within the filters component. 
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-220)

[FE]: Move "project size" filter to sidebar

---

client/src/app/layout.tsx
client/src/containers/intro-modal/index.tsx
client/src/lib/utils.ts
e2e/playwright.config.ts

- Integrated the IntroModal component into the RootLayout for user onboarding.
- Implemented IntroModalManager to manage modal visibility using local storage.
- Updated Playwright configuration to simulate user preferences for the intro modal during tests.
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-203)

[FE]: Add an intro modal

---

client/src/containers/projects/new/header.tsx
client/src/containers/projects/new/index.tsx

- Added router instance as a parameter to `onSubmit` function
- Navigation to preview page now happens after successful project creation
- Updated form submission handling in both header and main component
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-229)

fix: redirect preview onsubmit

---

client/src/components/session-checker/index.tsx

- Added `retry: false` to the token validation query options to prevent unnecessary retry attempts when the token is invalid
When a token is invalid, retrying the validation query is unnecessary and can cause unwanted side effects. This change ensures we immediately handle the invalid token case by signing out the user instead of attempting multiple validation requests.

fix: disable retry on token validation query

---

api/src/modules/import/import.repostiory.ts
api/test/integration/import/import.repository.spec.ts

This pull request includes changes to the `ImportRepository` class and adds new integration tests to ensure the correct behavior of the import functionality.
Changes to the `ImportRepository` class:
* [`api/src/modules/import/import.repository.ts`](diffhunk://#diff-a7f7a9963ea5c5c2c3ea37d5ac6e435be607b406814aa09d2811ff7163019358L37-R41): Modified the `importProjectScorecard` method to use the 'READ COMMITTED' isolation level and added logic to clear existing project scorecards before saving new ones.
Addition of integration tests:
* [`api/test/integration/import/import.repository.spec.ts`](diffhunk://#diff-34dc2be2409c131573dd04ec806227faa059af897eb9632fd762cf13ad080d41R1-R38): Added new integration tests to verify that previous project scorecards are wiped before importing new ones. This …

[TBCCT-249] feat(api): Ensure that the project scorecards are wiped before new ones are imported

---

client/src/containers/overview/table/view/overview/index.tsx

This PR improves the sorting behavior of the overview table by ensuring it always maintains a default sort state.
- Added a `DEFAULT_SORTING` constant for better maintainability
- Implemented a sorting handler that enforces default sorting when all sorts are cleared
- Table now consistently sorts by project name (descending) when no other sort is applied
[TBCCT-253](https://vizzuality.atlassian.net/browse/TBCCT-253)
[TBCCT-253]: https://vizzuality.atlassian.net/browse/TBCCT-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ensure default sorting persists in overview table

---

client/src/containers/overview/table/utils.ts
client/src/containers/overview/table/view/overview/index.tsx
shared/schemas/query-param.schema.ts

**Sort Order Updates and Column Sort Title Refactoring**
This PR includes the following changes:
- Adds a new `getColumnSortTitle` utility function to handle column sorting titles
- Fixes sort order direction in API queries (changes `-` prefix logic)
- Updates default sorting for project names to ascending order
- Refactors column header title logic to use the new utility function

fix: sorting overview table

---

api/src/modules/admin/admin.controller.ts
backoffice/resources/users/user.actions.ts

This pull request includes changes to the authentication mechanism in the admin module and user actions. The most important changes are:
Authentication mechanism updates:
* [`api/src/modules/admin/admin.controller.ts`](diffhunk://#diff-a106c988378f0b821c80c0e990def2145a84cc09c93798bb0bbfbe89ffe59cf8L3-R12): Replaced `JwtAuthGuard` with `JwtCookieAuthGuard` in the `AdminController` to switch from token-based to cookie-based authentication.
User action updates:
* [`backoffice/resources/users/user.actions.ts`](diffhunk://#diff-ebd7fd4dbe721eb4dc96e7ecf7957964e1a67f48545dbae592e2b8bdf60b9831L23-R27): Changed the authorization method in `createUserAction` to use cookies instead of the `Authorization` header for session-based authentication.

[bug/TBCCT-268] Fix integration between adminjs and API. The request made by adminjs to the API are authenticated via session cookie

---

client/src/components/session-checker/index.tsx
client/src/lib/utils.ts

- Updated private routes to include project detail and edit pages (`/projects/[uuid]` and `/projects/[uuid]/edit`)
- Modified session checker to validate accesstoken globally instead of only on private routes
- Updated sign-out behavior to redirect only when on private paths
This improves the user experience by maintaining consistent session state across all pages while ensuring proper authentication for protected routes. The sidebar navigation will now correctly reflect the user's login status regardless of which page they're viewing.

fix: session handling and private routes

---

api/src/modules/config/app-config.module.ts
api/src/modules/config/env-config.schema.ts

This pull request introduces changes to improve the validation of environment variables in the configuration module. The primary changes include the addition of a new schema validation using `zod` and the removal of the previous manual validation logic.
* [`api/src/modules/config/app-config.module.ts`](diffhunk://#diff-e132909938ae0bb299f3f36bdc9e110c1b52f5a5407ff9593894a94874fc5f0aR7): Added the import for `validateEnvConfig` and replaced the manual validation logic with the new `validateEnvConfig` function. [[1]](diffhunk://#diff-e132909938ae0bb299f3f36bdc9e110c1b52f5a5407ff9593894a94874fc5f0aR7) [[2]](diffhunk://#diff-e132909938ae0bb299f3f36bdc9e110c1b52f5a5407ff9593894a94874fc5f0aL17-R22)
* [`api/src/modules/config/env-variables-config.schema.ts`](diffhunk://#diff-44cf39540f80c68fa3518 …

feat(api): Create a zod schema to validate the environment configuration

---

api/src/modules/config/env-config.schema.ts

This pull request includes a small change to the `envConfigSchema` in the `api/src/modules/config/env-config.schema.ts` file. The change removes the `API_URL` configuration parameter.
* [`api/src/modules/config/env-config.schema.ts`](diffhunk://#diff-6797fbb6bfb10a6c1238712e8e0613fff7c75d8e902f3691c3f92251957d2a84L14): Removed the `API_URL` configuration parameter from the `envConfigSchema`.

fix(api): Remove unneeded env variable validation

---

client/src/components/ui/table.tsx
client/src/containers/overview/table/utils.tsx
client/src/containers/overview/table/view/key-costs/index.tsx
client/src/containers/overview/table/view/overview/index.tsx
client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
e2e/tests/projects/projects-overview-table.spec.ts

This pull request includes several changes to the table components and their usage in various parts of the application. The main focus is on improving the table's appearance and functionality, as well as adding new utility components for better code reuse.
Improvements to table components:
* [`client/src/components/ui/table.tsx`](diffhunk://#diff-8fb400981d306228d89c48b0fc071e12e28b02b56fbf40856c54e48c1bd0967aL25-R29): Modified the `ScrollableTable` and `TableHead` components to ensure the table takes full height and adjusted the table head styles. [[1]](diffhunk://#diff-8fb400981d306228d89c48b0fc071e12e28b02b56fbf40856c54e48c1bd0967aL25-R29) [[2]](diffhunk://#diff-8fb400981d306228d89c48b0fc071e12e28b02b56fbf40856c54e48c1bd0967aL94-R94)
Enhancements to table utilities:
* …

[N/A] consistent "no results" in tables

---

client/src/containers/projects/custom-project/annual-project-cash-flow/utils.ts
client/src/containers/projects/custom-project/cost-details/table/utils.ts
client/src/containers/projects/form/setup/index.tsx
shared/schemas/assumptions/assumptions.enums.ts

- Updated "Community benefit sharing fund" label to "Landowner/community benefit share"
- Fixed radio group in project setup form to use controlled `value` prop instead of `defaultValue`
- [TBCCT-285](https://vizzuality.atlassian.net/browse/TBCCT-285)
[TBCCT-285]: https://vizzuality.atlassian.net/browse/TBCCT-285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: ecosystem radiobox selection + update label

---

api/src/modules/custom-projects/custom-projects.service.ts
api/test/integration/custom-projects/custom-projects-create.spec.ts

This pull request includes several changes to the `custom-projects` module, specifically adding a new assumption for carbon price and updating related tests. The most important changes are:
* [`api/src/modules/custom-projects/custom-projects.service.ts`](diffhunk://#diff-a450b42f83aa743e906c235e1dbcc649854328c6951985e9bcaf6a40b6029eacR66-R68): Added a check to include `initialCarbonPriceAssumption` in `additionalAssumptions` if it is provided in the DTO.
* [`api/test/integration/custom-projects/custom-projects-create.spec.ts`](diffhunk://#diff-bfc98e374a31af4eb816dadb67f4cab3fa008a3984df106cce20aca6e9f74888L73-R74): Updated the expected values for `totalCostNPV` and `totalCost` in the integration tests to reflect the changes in the service logic.
* …

Use initial carbon price assumption

---

api/src/modules/custom-projects/custom-projects.service.ts
api/test/integration/custom-projects/custom-projects-read.spec.ts
shared/entities/custom-project.entity.ts

Removes unnecessary user joins from custom project queries. This change prevents user data from being included in API responses, improving data privacy.
- Removed `leftJoinAndSelect` for user data in `extendGetByIdQuery`
- Removed `leftJoinAndSelect` for user data in `extendFindAllQuery`
- Updated where clauses to use `customProject.user_id` directly
Previously, we were unnecessarily including user data in our query results and API responses. This change improves data privacy by only returning the essential custom project data.

refactor: remove user joins from custom project queries

---

client/src/containers/projects/form/assumptions/index.tsx
client/src/containers/projects/form/constants.ts
client/src/containers/projects/form/cost-inputs-overrides/capex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/opex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/other/index.tsx
client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
client/src/containers/projects/form/table/index.tsx
client/src/containers/projects/form/utils.ts
client/src/containers/projects/utils.ts

1. **Table Component Refactoring**
- Extracted common table logic into a reusable `FormTable` component
- Reduced code duplication across multiple form sections (assumptions, capex, opex, other)
2. **Default Form Values**
- Added centralized default values in `constants.ts`
- Updated form initialization to use consistent defaults
- Added default value for project specific sequestration rate
3. **Minor Improvements**
- Updated number formatting to remove decimal places in table cells
- [TBCCT-297](https://vizzuality.atlassian.net/browse/TBCCT-297)
[TBCCT-297]: https://vizzuality.atlassian.net/browse/TBCCT-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: updated default values custom project form + refactor form tables

---

client/src/containers/projects/form/cost-inputs-overrides/capex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/opex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/other/index.tsx
client/src/containers/projects/form/setup/index.tsx

This pull request includes changes to refactor the form handling in multiple components to use the `useFormValues` hook instead of `useFormContext`. This change aims to streamline the code and improve consistency across the project.
Refactoring form handling:
* [`client/src/containers/projects/form/cost-inputs-overrides/capex/index.tsx`](diffhunk://#diff-dfaabd9ecb243e346ab21fb26426590bd1b058a4484287a8709b959d071bc33eL1-L2): Replaced `useFormContext` with `useFormValues` for retrieving form values in `CapexCostInputsTable`. [[1]](diffhunk://#diff-dfaabd9ecb243e346ab21fb26426590bd1b058a4484287a8709b959d071bc33eL1-L2) [[2]](diffhunk://#diff-dfaabd9ecb243e346ab21fb26426590bd1b058a4484287a8709b959d071bc33eL22-R20) [[3]](diffhunk://#diff-dfaabd9ecb243e346ab21fb26426590bd1b058a4484287a8709b959d0 …

[TBCCT-312] defaults restoration activity to make sure costs are calculated

---

client/src/containers/projects/form/setup/index.tsx

**NOTE: we need BE to restore one of the tables in the database to ensure this change works.**
This pull request includes a change to the `SetupProjectForm` component in `client/src/containers/projects/form/setup/index.tsx`. The change updates the query key and the method used to retrieve country options for custom projects.
Changes to `SetupProjectForm` component:
* Updated the query key from `queryKeys.countries.all` to `queryKeys.customProjects.countries`.
* Changed the method used to retrieve country options from `client.projects.getProjectCountries.useQuery` to `client.customProjects.getAvailableCountries.useQuery`.
* Reformatted the mapping function to improve readability.
Related to: https://vizzuality.atlassian.net/browse/TBCCT-312

[TBCCT-312?] harmonizes countries fetching in custom project form

---

api/test/integration/calculations/fixtures/restoration-mexico-mangroves.ts
api/test/integration/custom-projects/custom-projects-setup.spec.ts
shared/schemas/assumptions/assumptions.enums.ts

This pull request includes updates to the custom projects setup and assumptions enums to include a new assumption, "Carbon price."
Changes to custom projects setup:
* [`api/test/integration/custom-projects/custom-projects-setup.spec.ts`](diffhunk://#diff-b91e7fa38b414665b5837150fd1bf381a04a1affd5a12b2835fc7edc6ef8cff3L51-R56): Modified the test expectation to account for the new "Carbon price" assumption, increasing the expected data length from 7 to 8.
Changes to assumptions enums:
* [`shared/schemas/assumptions/assumptions.enums.ts`](diffhunk://#diff-60224e7ca44abce666ca7a85d22f45d8e2c58fac26deb601ab487853e4b8c032R15): Added "Carbon price" to the list of common overridable assumption names.

feat(api): Add initial carbon price default value in the /assumptions endpoint

---

backoffice/resources/project-size/project-size.resource.ts
shared/entities/cost-inputs/project-size.entity.ts

This pull request includes changes to the `ProjectSizeResource` in the backoffice module and the `project-size.entity.ts` file in the shared module. The changes are primarily focused on simplifying the properties and removing unnecessary imports.
Changes to `ProjectSizeResource`:
* Removed the `source` property from `listProperties`, `showProperties`, and `editProperties` arrays (`backoffice/resources/project-size/project-size.resource.ts`).
* Removed the `source` property definition from the `properties` object (`backoffice/resources/project-size/project-size.resource.ts`).
Changes to `project-size.entity.ts`:
* Removed the import statement for `ModelComponentSource` as it is no longer used (`shared/entities/cost-inputs/project-size.entity.ts`).

fix: Remove ProjectSize -> ModelComponentSource relationship

---

api/src/modules/methodology/methodology.repository.ts

This pull request includes changes to the `MethodologyRepository` class in the `methodology.repository.ts` file to improve the handling and aggregation of source data in SQL queries. The most important changes include modifying the SQL query to use a subquery for source aggregation and ensuring proper aliasing.
Changes to SQL query handling:
* [`api/src/modules/methodology/methodology.repository.ts`](diffhunk://#diff-92d32f6cd50ecf42229438cfd17545920ce8096be812381d7f96c89f6c3bb603L37-R37): Modified the SQL query to use `sources_subquery` for source type and sources aggregation in the `JSONB_OBJECT_AGG` function.
* [`api/src/modules/methodology/methodology.repository.ts`](diffhunk://#diff-92d32f6cd50ecf42229438cfd17545920ce8096be812381d7f96c89f6c3bb603L58-R58): Ensured proper aliasing of …

Fix model component sources subquery because it was incompatible with the env postgres version

---

client/src/containers/projects/custom-project/annual-project-cash-flow/chart/index.tsx
client/src/containers/projects/custom-project/annual-project-cash-flow/index.tsx
client/src/containers/projects/custom-project/annual-project-cash-flow/utils.ts
client/src/containers/projects/custom-project/index.tsx
client/src/hooks/use-custom-project-output.ts

- Added a breakeven point reference line to the cash flow chart
- Updated chart tooltips to show different labels based on carbon revenue coverage type (OpEx vs CapEx+OpEx)
- Added visual indicator for breakeven point in chart legend
- [TBCCT-317](https://vizzuality.atlassian.net/browse/TBCCT-317)
- [TBCCT-315](https://vizzuality.atlassian.net/browse/TBCCT-315)
- [TBCCT-321](https://vizzuality.atlassian.net/browse/TBCCT-321)
[TBCCT-317]: https://vizzuality.atlassian.net/browse/TBCCT-317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-315]: https://vizzuality.atlassian.net/browse/TBCCT-315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-321]: …

Add Breakeven Point and Revenue Coverage to Cash Flow Chart

---

client/src/containers/projects/form/restoration-plan/index.tsx
client/src/containers/projects/form/utils.ts
client/tests/projects/form/utils.test.ts
shared/schemas/custom-projects/create-custom-project.schema.ts

- Extracted restoration plan table data generation logic into a separate utility function `getRestorationPlanTableData`
- Added input validation for project length values
- Added unit tests for the new utility function
- Introduced `MAX_PROJECT_LENGTH` constant (40 years) for better maintainability
- Added optional function argument to adjust maxProjectLength

fix: form crash restoration project-length input

---

client/src/containers/projects/form/constants.ts
client/src/containers/projects/form/cost-inputs-overrides/capex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/opex/index.tsx
client/src/containers/projects/form/cost-inputs-overrides/other/index.tsx
client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
client/src/containers/projects/form/utils.ts
client/tests/projects/form/default-values.test.tsx

This pull request includes changes to the `client/src/containers/projects/form` directory to enhance the handling of restoration projects. The most important changes involve updating constants, modifying form setup, and ensuring default values are correctly applied.
* [`client/src/containers/projects/form/constants.ts`](diffhunk://#diff-2ae025fd6400b66305aeeaf59766c0d3e22af6ebfd35f98f65b4439823d32dbdL1-R4): Added `RESTORATION_ACTIVITY_SUBTYPE` and `SEQUESTRATION_RATE_TIER_TYPES` to imports and updated `DEFAULT_RESTORATION_FORM_VALUES` to include new parameters such as `restorationActivity`, `tierSelector`, and `restorationYearlyBreakdown`. [[1]](diffhunk://#diff-2ae025fd6400b66305aeeaf59766c0d3e22af6ebfd35f98f65b4439823d32dbdL1-R4) …

[TBCCT-327] fixes missing plantingSuccessRate value during form validation

---

api/test/integration/custom-projects/custom-projects-create.spec.ts
api/test/integration/custom-projects/custom-projects-update.spec.ts
api/test/integration/custom-projects/custom-projects-validations.spec.ts
client/src/containers/projects/form/setup/index.tsx
client/src/containers/projects/form/utils.ts
shared/lib/stubs/custom-project.stub.ts
shared/schemas/custom-projects/create-custom-project.schema.ts

This pull request focuses on enhancing the validation and schema definitions for creating custom projects. The changes ensure that required fields are properly validated and that the schemas enforce the presence of necessary data.
* Added validation checks for missing required fields in custom project creation tests. These checks include `assumptions`, `costInputs`, and specific parameters within the project-specific emission factors. [[1]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012R55-R83) [[2]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012R127-L106) [[3]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012R177-R203) [[4]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c …

fix: Apply missing constraints to the custom-project schema

---

api/src/modules/import/services/entity.preprocessor.ts
shared/entities/project-score-card/value-object/availability-of-alternating-funding.value-object.ts
shared/entities/project-score-card/value-object/availability-of-experienced-labor.value-object.ts
shared/entities/project-score-card/value-object/biodiversity-benefit.value-object.ts
shared/entities/project-score-card/value-object/coastal-protection-benefits.value-object.ts
shared/entities/project-score-card/value-object/finantial-feasability.value-object.ts
shared/entities/project-score-card/value-object/implementation-feasibility.value-object.ts
shared/entities/project-score-card/value-object/legal-feasibility.value-object.ts
shared/entities/project-score-card/value-object/project-score-card-field.value-object.ts
shared/entities/project-score-card/value-object/security-rating.value-object.ts
shared/entities/project-score-card/value-object/social-feasibility.value-object.ts
shared/entities/project-score.utils.ts

This pull request introduces a significant refactor of the project scorecard system by replacing the `convertNumberToProjectScore` method with dedicated value object classes for each scorecard field. The changes include modifications to the `EntityPreprocessor` class and the addition of several new value object classes.
* Replaced `convertNumberToProjectScore` method calls with corresponding value object method calls for various project scorecard fields.
* Removed the `convertNumberToProjectScore` method as it is no longer needed.
* Added `AvailabilityOfAlternatingFunding` class to handle conversion between numbers and project scores.
* Added `AvailabilityOfExperiencedLabor` class to handle conversion between numbers and project scores.
* Added `BiodiversityBenefit` class to handle …

fix(api): Scorecard rating number/string convertion based on each field

---

backoffice/components/dashboard.tsx
backoffice/index.ts
backoffice/public/back-button.css
backoffice/public/back-button.js

This pull request includes several changes to the back office dashboard, including the addition of a back button and updates to the root path configuration. The most important changes are grouped into two themes: codebase improvements and UI enhancements.
* [`backoffice/index.ts`](diffhunk://#diff-748e5cd1c2a59cf8dfcd0e9645994a676a6662143cc6dc23fa52213c32a37405R47): Added `path` import and updated the `start` function to include a new `ROOT_PATH` constant. This constant is used to define the root path for assets and static files. [[1]](diffhunk://#diff-748e5cd1c2a59cf8dfcd0e9645994a676a6662143cc6dc23fa52213c32a37405R47) [[2]](diffhunk://#diff-748e5cd1c2a59cf8dfcd0e9645994a676a6662143cc6dc23fa52213c32a37405R56) [[3]](diffhunk://#diff-748e5cd1c2a59cf8dfcd0e9645994a676a6662143cc6dc23fa52213c3 …

[TBCCT-237] Add back button to navigate to the front office

---

api/src/modules/calculations/cost.calculator.ts
api/test/integration/calculations/fixtures/conservation-indonesia-mangrove.ts
api/test/integration/calculations/fixtures/restoration-china-salt-marsh.ts
api/test/integration/calculations/fixtures/restoration-mexico-mangroves.ts
client/src/constants/tooltip.tsx
client/src/containers/projects/custom-project/index.tsx
client/src/containers/projects/custom-project/summary/index.tsx
client/src/hooks/use-custom-project-output.ts
shared/dtos/custom-projects/custom-project-output.dto.ts

This pull request includes changes to update the terminology from "Community benefit sharing fund" to "Landowner/community benefit share" across various files in the codebase. The changes ensure consistency in the terminology used throughout the project.
Terminology update:
* [`api/src/modules/calculations/cost.calculator.ts`](diffhunk://#diff-f3a786faa816de52227b70d447bbed13537c00886ffc27518b616149b4a2e4d7L237-R237): Updated the key name in the `CostCalculator` class.
* [`shared/dtos/custom-projects/custom-project-output.dto.ts`](diffhunk://#diff-eee98ecbdd9edf2e440d8945d6ed3a7e93e8b54f1a32b12aae251207ccd1dc6eL18-R18): Updated the type definition and sorted keys for `CustomProjectSummary`. [[1]](diffhunk://#diff-eee98ecbdd9edf2e440d8945d6ed3a7e93e8b54f1a32b12aae251207ccd1dc6eL18-R18) …

[TBCCT-343] Landowner/community benefit share is not correct. 5% instead of 50% and renaming

---

client/src/containers/overview/hooks.ts
client/src/containers/overview/project-details/footer/index.tsx
client/src/containers/overview/project-details/index.tsx
client/src/containers/overview/project-details/utils.ts
client/src/containers/overview/table/index.tsx
client/src/containers/overview/table/view/key-costs/index.tsx
client/src/containers/overview/table/view/overview/index.tsx
client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
client/src/containers/overview/utils.ts
pnpm-lock.yaml
pnpm-workspace.yaml

1. Created a new `useProjectDetails` hook to centralize project details management
2. Added dynamic project size label in the footer component
3. Improved table row styling and interactions
4. Fixed navigation between tables while maintaining project details state
5. Added proper Next.js Link components and accessibility improvements
6. Created utility functions for consistent data handling
- [TBCCT-329](https://vizzuality.atlassian.net/browse/TBCCT-329)
- [TBCCT-339](https://vizzuality.atlassian.net/browse/TBCCT-339)
[TBCCT-329]: https://vizzuality.atlassian.net/browse/TBCCT-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-339]: https://vizzuality.atlassian.net/browse/TBCCT-339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

fix: show correct project size + refactor overview table

---

backoffice/resources/emission-factors/emission-factors.resource.ts

This pull request includes a small change to the `backoffice/resources/emission-factors/emission-factors.resource.ts` file. The change removes the `emissionFactor` property from the `EmissionFactorsResource` object.
* [`backoffice/resources/emission-factors/emission-factors.resource.ts`](diffhunk://#diff-fba7695dfaaed317a8d3492550e260f86269082f04262cb8e1eabbdca837c3ddL45-L47): Removed the `emissionFactor` property from the `EmissionFactorsResource` object.

fix(back office): Remove emission factors columns cause it is not in the model anymore

---

client/src/containers/projects/custom-project/cost-details/table/utils.ts
client/src/containers/projects/custom-project/index.tsx
client/src/hooks/use-custom-project-output.ts
shared/dtos/custom-projects/custom-project-output.dto.ts

This pull request introduces several changes to improve the handling of custom project cost details in the project management system. The most important changes include the introduction of separate label maps for conservation and restoration projects, updating the `parseCostDetailsForTable` function to handle different project activities, and modifying the `useCustomProjectOutput` hook to pass the activity type when parsing cost details.
* [`client/src/containers/projects/custom-project/cost-details/table/utils.ts`](diffhunk://#diff-b7531b4a5e9fe352796c5ca575121807b801f16daad98dfab74d901e1cf71b5fR6-R31): Introduced `CONSERVATION_PROJECT_COST_LABELS` and `RESTORATION_PROJECT_COST_LABELS` to handle different labels for conservation and restoration projects.
* …

fix(client): Remove implementation labor from cost details for conservation projects

---

backoffice/components/molecules/many-2-many-sources.tsx

This pull request includes several changes to the `Many2ManySources` component in the `backoffice` module to enhance functionality and improve code clarity. The most important changes include adding a search string state, updating the data fetching function to use this search string, and ensuring the component re-fetches data when the search string changes.
Enhancements to functionality:
* [`backoffice/components/molecules/many-2-many-sources.tsx`](diffhunk://#diff-b2602c572a6898cbdbdd52549df3691ade9e22ea7dc7136b6bb19ae9d64e3fc6R78): Added a new state `sourceSearchString` to manage the search input for filtering available sources.
* [`backoffice/components/molecules/many-2-many-sources.tsx`](diffhunk://#diff-b2602c572a6898cbdbdd52549df3691ade9e22ea7dc7136b6bb19ae9d64e3fc6L103-R112): …

fix(backoffice): Pagination issues in the back office when adding sources (Not all sources are findable)

---

api/src/modules/import/parser/data-ingestion.xlsx-parser.ts

This pull request includes a significant change to the `DataIngestionExcelParser` class in the `data-ingestion.xlsx-parser.ts` file. The change improves the handling of rows with 'NoData' values by converting them to `undefined` during the parsing process.
Improvements to data parsing:
* [`api/src/modules/import/parser/data-ingestion.xlsx-parser.ts`](diffhunk://#diff-7261aa4561bd64546afb142afbd91dc3c312e82695fb75b226b83bc8e537004fL37-R49): Modified the `parsedTab` construction to map over each row and replace 'NoData' values with `undefined`.

fix(api): Solve the NaN issue during the excel import

---

backoffice/components/molecules/many-2-many-sources.tsx

This pull request includes changes to the `backoffice/components/molecules/many-2-many-sources.tsx` file, primarily focused on enhancing the user interface and improving the code structure. The most important changes include adding a new `Link` component and updating the import statements for better readability.
User Interface Enhancements:
* Added a `Link` component to wrap the `Badge` displaying the source type and name, allowing users to navigate to the detailed view of the source.
Code Structure Improvements:
* Updated import statements to include `Link` from `@adminjs/design-system` and organized the imports for better readability.

feat(backoffice): Related sources should be clickable and open their detail view when clicked

---

api/src/modules/import/import.service.ts

This pull request includes a change to improve the error message in the `ImportService` class. The change modifies the exception message for a failed import to provide a clearer and more specific error description.
* [`api/src/modules/import/import.service.ts`](diffhunk://#diff-695dbebee9d4a7e0e05fd8c18fa8c56c5526003239ff604eb4b8931839c329b8L76-R76): Changed the `ConflictException` message to 'The excel file could not be imported' to provide a more user-friendly error message.

fix(api): Remove stack trace from the response body

---

backoffice/components/atoms/country-selector.tsx
backoffice/components/config/Config.ts
backoffice/components/index.tsx
backoffice/index.ts
backoffice/resources/projects/projects.resource.ts

This pull request introduces a new `CountrySelector` component for the backoffice application. The changes include the creation of the component, configuration updates, and integration into the existing project resources. The most important changes are as follows:
* [`backoffice/components/atoms/country-selector.tsx`](diffhunk://#diff-2e974719d37b42d49d536d39cc5455b077e265e196237a24c30770139d6df0dcR1-R56): Added a new `CountrySelector` component that fetches available countries from an API and displays them in a dropdown menu.
* [`backoffice/components/config/Config.ts`](diffhunk://#diff-08a2d10595d90264db4c2af267802e915eb205a871432d5206e33768d46af08aR1-R3): Introduced a new configuration file to store the `ADMINJS_CONFIG_ENDPOINT` constant.
* …

fix: populate upsert back office country selector using the custom api endpoint

---

client/src/containers/overview/map/layers/projects/index.tsx
client/src/containers/overview/map/popup/index.tsx

This pull request includes updates to the `ProjectsLayer` and `CostAbatementPopup` components in the `client/src/containers/overview/map` directory. The changes involve modifying queries and updating table headers and descriptions.
Changes to queries and data fetching:
* [`client/src/containers/overview/map/layers/projects/index.tsx`](diffhunk://#diff-75746c8395816d4de3c48010210c66d0b2eef6fb3dfde641c6aa205440262370L20-R20): Updated the query method from `getProjectsMap` to `getProjectsMapV2` to fetch project data.
Changes to UI text:
* [`client/src/containers/overview/map/popup/index.tsx`](diffhunk://#diff-611d5db67170296f3da4bd0b5f368d847e0ac4e153f5bde17daf4e4f3c58c810L27-R27): Updated the table header from "Cost (total, USD)" to "AVG Cost (USD)" for clarity.
* …

[TBCCT-379/291]uses v2 map endpoint to retrieve abatement per country

---

client/src/containers/projects/form/number-form-item.tsx
client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
e2e/tests/custom-projects/edit-custom-project.spec.ts
shared/schemas/custom-projects/custom-project-form.constants.ts

- Modified `NumberFormItem` component to properly handle percentage values
- Updated `plantingSuccessRate` default value from 0.8 to 0.6
- Made planting success rate field editable in restoration project details
- Fixed percentage display in form inputs
- Updated e2e test to reflect new percentage-based value handling
- [TBCCT-387](https://vizzuality.atlassian.net/browse/TBCCT-387)
[TBCCT-387]: https://vizzuality.atlassian.net/browse/TBCCT-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: changed default value of plantingSuccessRate and enable form input

---

.github/workflows/e2e-tests.yml
e2e/package.json
e2e/tests/custom-projects/create-custom-project.spec.ts

This pull request includes a small change to the `.github/workflows/e2e-tests.yml` file. The change updates the syntax for defining environment variables in the `jobs:` section, replacing the `environment` block with an `env` block.

chore: Fix e2e-tests.yml

---

api/src/modules/auth/authentication.controller.ts
api/src/modules/custom-projects/custom-projects.controller.ts
api/src/modules/import/import.controller.ts
api/src/modules/users/users.controller.ts
api/test/integration/auth/create-user.spec.ts
api/test/integration/auth/delete-account.spec.ts
api/test/integration/auth/password-recovery-reset-password.spec.ts
api/test/integration/auth/password-recovery-send-email.spec.ts
api/test/integration/auth/sign-in.spec.ts
api/test/integration/auth/sign-up.spec.ts
api/test/integration/auth/validate-token.spec.ts
api/test/integration/import/import-scorecard.spec.ts
api/test/integration/import/import.spec.ts
api/test/integration/users/users-email-update.spec.ts
api/test/integration/users/users-me.spec.ts
backoffice/index.ts
client/src/containers/profile/account-details/schema.ts
shared/entities/users/roles.enum.ts
shared/entities/users/user.entity.ts

This pull request updates role-based access control across the application, changing the default role for users from `ROLES.PARTNER` to `ROLES.USER`. The changes affect both the core application logic and the associated integration tests.
* Updated the default role assigned during user registration in `AuthenticationController` to `ROLES.USER` (`api/src/modules/auth/authentication.controller.ts`).
* Adjusted required roles for various endpoints in `CustomProjectsController`, `ImportController`, and `UsersController` to replace `ROLES.PARTNER` with `ROLES.USER`. [[1]](diffhunk://#diff-cc9c8bff38622ff15dd4ba62ed57da7aa1af212d09902ea07100a2182a45147eL90-R90) [[2]](diffhunk://#diff-cc9c8bff38622ff15dd4ba62ed57da7aa1af212d09902ea07100a2182a45147eL106-R106) …

fix: User ROLES.PARTNER to ROLES.USER and back office navigation tab names

---

api/src/modules/calculations/data.repository.ts
api/test/integration/custom-projects/custom-projects-setup.spec.ts
shared/dtos/custom-projects/activity-types-defaults.ts

**This PR adds Planting Success Rate assumption to the activity defaults endpoint, so it can be dyamically populated in the custom project creation form**
Relevant ticket: https://vizzuality.atlassian.net/browse/TBCCT-406
This pull request introduces changes to enhance the handling of restoration activity data by including a new `plantingSuccessRate` field and updating related logic, tests, and data structures. The most important changes focus on improving the repository method, updating the test suite, and modifying the DTOs to support the new field.
* **Repository logic update**:
- In `data.repository.ts`, replaced the `findOne` method with `findOneOrFail` for retrieving restoration activity data and added a query to fetch the `plantingSuccessRate` from the assumptions repository. The …

TBCCT-406: Retrieve planting success rate as part of activity defaults

---

client/src/containers/projects/form/setup/activity/index.tsx
client/src/containers/projects/form/setup/conservation-project-details/index.tsx
e2e/lib/utils.ts
e2e/tests/custom-projects/edit-custom-project.spec.ts

https://vizzuality.atlassian.net/browse/TBCCT-383
This pull request introduces several updates to the project setup and testing workflows, focusing on improving form handling, adding new utility functions, and enhancing test reliability. Key changes include refactoring imports, adding default values for form parameters, introducing a new utility for restoration projects, and updating Playwright tests for better consistency and coverage.
* Consolidated imports in `client/src/containers/projects/form/setup/activity/index.tsx` for better readability and maintenance.
* Added logic to set a default value for the `lossRateUsed` parameter in the `Activity` component when undefined, ensuring consistent form behavior.
* Updated the `RadioGroup` component in `ConservationProjectDetails` to use the …

[TBCCT-383] fixes undefined lossRate in restoration projects

---

api/test/integration/custom-projects/custom-projects-save.spec.ts
client/src/containers/methodology/table/data.tsx
client/src/containers/overview/project-details/utils.ts
client/src/containers/overview/table/toolbar/index.tsx
client/src/hooks/use-custom-project-output.ts
client/tests/projects/form/constants.ts

Task: https://vizzuality.atlassian.net/browse/TBCCT-410
This pull request standardizes terminology across the codebase by replacing the term "Community benefit sharing fund" with "Landowner/community benefit share" in various files. The changes ensure consistency in naming conventions and remove redundant code related to the old terminology.
* [`api/test/integration/custom-projects/custom-projects-save.spec.ts`](diffhunk://#diff-124179fd0dc8dfe83a9603ea28faa3eccc0706bfec20acf39bf1d89c1a4b42c9L82-R82): Updated the key `'Community benefit sharing fund'` to `'Landowner/community benefit share'` in test data.
* [`client/src/containers/methodology/table/data.tsx`](diffhunk://#diff-c8936b71b4513d5225c2f44ae0773f42d7685dead6acf5609fa5b256e65ee93bL219-R221): Renamed the `id` and updated the …

[TBCCT-410] replaces "Community benefit sharing fund" with "Landowner/community benefit share"

---

client/src/containers/projects/custom-project/cost-details/table/utils.ts

Task: https://vizzuality.atlassian.net/browse/TBCCT-424
This pull request modifies the way `RESTORATION_PROJECT_COST_LABELS` is constructed in the `utils.ts` file to improve flexibility and maintainability. The change replaces a static object spread pattern with a dynamic approach using `Object.fromEntries` and array slicing.
* [`client/src/containers/projects/custom-project/cost-details/table/utils.ts`](diffhunk://#diff-b7531b4a5e9fe352796c5ca575121807b801f16daad98dfab74d901e1cf71b5fL34-R38): Updated the `RESTORATION_PROJECT_COST_LABELS` definition to dynamically merge entries from `CONSERVATION_PROJECT_COST_LABELS` with the new `implementationLabor` label. This is achieved by slicing and recombining entries, allowing for better control over label ordering.

[TBCCT-424] cost details: moves implementation labor cost to capital expenditure

---

api/test/integration/custom-projects/custom-projects-validations.spec.ts
client/src/containers/projects/form/number-form-item.tsx
client/src/containers/projects/form/setup/conservation-project-details/loss-rate.tsx
e2e/tests/custom-projects/create-custom-project.spec.ts
shared/schemas/custom-projects/create-custom-project.schema.ts

This pull request updates the validation rules for "Project Specific Loss Rate" across the codebase to expand the acceptable range from `-0.3% to -0.001%` to `-100% to 0%`. It also includes minor refactoring changes to improve code readability and consistency in import ordering.
* [`api/test/integration/custom-projects/custom-projects-validations.spec.ts`](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012L111-R111): Updated test cases to reflect the new validation range for "Project Specific Loss Rate" and adjusted test data accordingly. [[1]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012L111-R111) [[2]](diffhunk://#diff-040b506e0f69f9191a8bcb6e0753ccce4b01ab36f3ca0c7ca06e699087f23012L125-R125) …

[N/A] updates project-specific loss rate range

---

client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
e2e/tests/custom-projects/create-custom-project.spec.ts

This pull request refactors the sequestration rate tier selection logic in the `RestorationProjectDetails` component to improve maintainability and enhance functionality. The changes include the introduction of a new `SEQUESTRATION_RATE_TIER_OPTIONS` constant for tier options and the removal of hardcoded logic for ecosystem defaults.
* [`client/src/containers/projects/form/setup/restoration-project-detail/index.tsx`](diffhunk://#diff-d2d621298d4d4d9f5b677461c9bde02aec797b48304634606cca5ea07ae5207eR79-R88): Added a `SEQUESTRATION_RATE_TIER_OPTIONS` constant that dynamically generates tier options with labels and disabled states based on the ecosystem type. This replaces hardcoded tier logic.
* [`client/src/containers/projects/form/setup/restoration-project-detail/index.tsx`](diffhunk://#dif …

[TBCCT-431] disables T2 sequestration rate option when Mangroves ecosystem is not selected

---

client/src/containers/projects/custom-project/annual-project-cash-flow/chart/index.tsx

This pull request makes adjustments to the `CashflowChart` component in `client/src/containers/projects/custom-project/annual-project-cash-flow/chart/index.tsx`, including reordering imports and relocating the `ReferenceLine` rendering logic to improve code organization and readability.
* Reordered the imports to group related items together and ensure consistent organization. Specifically, moved `ReferenceLine` within the `recharts` imports and adjusted the order of utility imports.
* Removed the `ReferenceLine` rendering logic from its previous position and relocated it to a later part of the `CashflowChart` component, ensuring it appears after the `Bar` elements are defined. This improves the logical flow of rendering and aligns with visual hierarchy. …

[TBCCT-428] brings breakeven line forward in chart

---

client/src/containers/projects/form/setup/restoration-project-detail/index.tsx

This pull request makes a small update to the `RestorationProjectDetails` component to improve the clarity of displayed information. Specifically, it updates tooltip content and the placeholder text for a data field.
* Updated the tooltip content to provide a more descriptive explanation: "Growth rate and carbon accumulation rate in soils." (`client/src/containers/projects/form/setup/restoration-project-detail/index.tsx`, [client/src/containers/projects/form/setup/restoration-project-detail/index.tsxL234-R240](diffhunk://#diff-d2d621298d4d4d9f5b677461c9bde02aec797b48304634606cca5ea07ae5207eL234-R240))
* Changed the placeholder text for the `ReadonlyInput` field to "tCO2e/ha/yr" for better context. (`client/src/containers/projects/form/setup/restoration-project-detail/index.tsx`, …

[TBCCT-432] updates unit and description of Tier 2 - Country-specific rate

---

client/src/containers/projects/form/setup/conservation-project-details/loss-rate.tsx

This pull request includes a small change to the `LossRate` component in `loss-rate.tsx`. The `isPercentage` prop was removed from the component's usage, simplifying its implementation.

[TBCCT-345] sends projectSpecificLossRate without percentage formatting

---

client/src/containers/auth/forgot-password/email-form/index.tsx
client/src/containers/auth/signin/form/index.tsx
e2e/tests/auth/delete-account.spec.ts

This pull request refactors the handling of user notifications in the Forgot Password and Sign-In forms to streamline the code and improve user feedback. The changes primarily replace the use of state-based error messages with the `toast` notification system and simplify the code by removing unused variables.
* Replaced the `apiResponseToast` usage with the `toast` function for displaying success and error messages during the password recovery process.
* Updated the dependency array of the `handleForgotPassword` callback to remove the unused `apiResponseToast` dependency.
* Removed the `useState` hook for managing error messages and replaced it with the `toast` function to handle error notifications. [[1]](diffhunk://#diff-57861ba932977f8ff3a960175e7fb1c6c7b761ffba3f8c7086138eb52d23ba9cR29 …

[TBCCT-448] hides email leak and improves consistency of errors display

---

client/src/containers/overview/index.tsx

This pull request introduces a minor enhancement to the `Overview` component in `client/src/containers/overview/index.tsx`. It ensures that the map resizes properly when certain state changes occur, improving the user interface's responsiveness.
Enhancements to map resizing:
* [`client/src/containers/overview/index.tsx`](diffhunk://#diff-4132fd1974a92d212e088e860d1fa76acffc6f7929c857efa46ea1fe3a90b4d3R41-R50): Added a `useEffect` hook that triggers a delayed map resize whenever `filtersOpen` or `map` changes. This ensures the map adjusts dynamically after layout transitions.
* [`client/src/containers/overview/index.tsx`](diffhunk://#diff-4132fd1974a92d212e088e860d1fa76acffc6f7929c857efa46ea1fe3a90b4d3R3-R4): Imported `useEffect` from React to support the new functionality.

[TBCCT-441] resize map correctly after toggling filters

---

client/src/app/methodology/page.tsx
client/src/containers/methodology/sections/index.tsx
client/src/containers/methodology/sections/versions/index.tsx
client/src/containers/methodology/sections/versions/table.tsx
client/src/containers/methodology/table/data.tsx
client/src/lib/query-keys.ts

This pull request introduces a new "Versions" section to the methodology page, which documents changes to the calculation methodology over time. It includes updates to prefetch changelog data, integrates the new section into the methodology structure, and implements a table to display version details.
* Added prefetching of changelog data in `MethodologyPage` to optimize loading for the new "Versions" section (`client/src/app/methodology/page.tsx`).
* Imported and registered the `Versions` component in the `METHODOLOGY_SECTIONS` array to include it in the methodology page structure (`client/src/containers/methodology/sections/index.tsx`). [[1]](diffhunk://#diff-07da5e8a18a746af616939178b73dad92782986c64a8e38ec752976cf3fa8186R9-R10) …

[TBCCT-473] methodology: versions

---

client/src/containers/methodology/index.tsx
client/src/hooks/use-scroll-spy.ts

This pull request introduces improvements to the scroll spy behavior in the methodology section of the client application. The main changes involve adjusting the scroll detection sensitivity and refining how the current step is set when scrolling.
Scroll spy behavior adjustments:
* Increased the `threshold` value from 0.05 to 0.3 in the scroll spy options within `client/src/containers/methodology/index.tsx`, making the step change trigger less sensitive to small scrolls.
* Removed the logic that set the current step to `null` when no section was detected in `client/src/hooks/use-scroll-spy.ts`, ensuring the current step remains unchanged unless a new section is detected.

[TBCCT-482] fixes methodology section highlighting

---

client/src/containers/overview/table/view/overview/columns.tsx
client/src/containers/projects/custom-project/details/detail-item/index.tsx
client/src/containers/projects/custom-project/index.tsx
client/src/containers/projects/custom-project/left-over/index.tsx

This pull request introduces several UI and logic improvements to the custom project overview and details pages, focusing on clearer terminology, enhanced data display, and improved component flexibility. The most significant updates include renaming a column for clarity, enhancing the `LeftOver` component to handle new props and logic, and refining value display in project details.
**Terminology and Data Display Updates:**
* The "Abatement potential (tCO2e/yr)" column header in the overview table was renamed to "Credit potential (tCO2e/yr)" for improved clarity. Additionally, if the value is zero, the cell now displays "Minimal or insignificant loss rates" instead of "0".
* In the project details, the value display now uses a responsive text size class (`2xl:text-xl`) for better visual …

Front end tweaks

---

client/package.json
client/src/app/(overview)/page.tsx
client/src/app/auth/api/[...nextauth]/config.ts
client/src/app/auth/backoffice/signout/route.ts
client/src/app/projects/[id]/edit/page.tsx
client/src/containers/auth/signup/form/action.ts
package.json
pnpm-lock.yaml

This pull request updates dependencies in both the root and client `package.json` files to improve compatibility and build processes. The most significant change is the upgrade of the `next` framework to a newer major version.
Dependency upgrades:
* Upgraded the `next` dependency from version `14.2.26` to `15.4.7` in `client/package.json`, ensuring the project uses the latest features and security updates from the Next.js framework.
Build configuration adjustments:
* Changed the order of dependencies in the `pnpm.onlyBuiltDependencies` list in `package.json`, moving `bcrypt` before `esbuild` and adding `sharp` to the list, which may affect build optimization and dependency management.

[N/A] next@15.4.7
