Vizzuality/tnc-blue-carbon-cost-tool

- client/.env.development
- client/components.json
- client/package.json
- client/src/app/auth/api/[...nextauth]/config.ts
- client/src/app/auth/signin/page.tsx
- client/src/app/globals.css
- client/src/app/page.tsx
- client/src/app/profile/page.tsx
- client/src/components/ui/button.tsx
- client/src/components/ui/form.tsx
- client/src/components/ui/input.tsx
- client/src/components/ui/label.tsx
- client/src/containers/auth/signin/form/index.tsx
- client/src/containers/auth/signin/index.tsx
- client/src/containers/profile/index.tsx
- client/src/lib/queryClient.ts
- client/src/lib/utils.ts
- client/src/middleware.ts
- client/tailwind.config.ts
- pnpm-lock.yaml
> implement signing process and page

- client/package.json
- client/src/app/auth/(password)/forgot-password/[token]/page.tsx
- client/src/app/auth/(password)/forgot-password/layout.tsx
- client/src/app/auth/(password)/forgot-password/page.tsx
- client/src/app/auth/api/[...nextauth]/config.ts
- client/src/app/providers.tsx
- client/src/components/ui/toast/index.tsx
- client/src/components/ui/toast/toaster.tsx
- client/src/components/ui/toast/use-api-response-toast.ts
- client/src/components/ui/toast/use-toast.ts
- client/src/containers/auth/forgot-password/email-form/index.tsx
- client/src/containers/auth/forgot-password/new-password-form/index.tsx
- client/src/lib/query-client.ts
- client/src/lib/query-keys.ts
- pnpm-lock.yaml
This pull request includes various changes to the `client` package, focusing on adding new components, updating dependencies, and renaming files for consistency. The most important changes include the addition of new password management pages, a toast notification system, and the renaming of a key utility file.
https://vizzuality.atlassian.net/browse/TBCCT-25
https://vizzuality.atlassian.net/browse/TBCCT-29
https://vizzuality.atlassian.net/browse/TBCCT-30
* `client/src/app/auth/(password)/forgot-password/[token]/page.tsx`: Added `NewPasswordForm` to handle new password creation. ([client/src/app/auth/(password)/forgot-password/[token]/page.tsxR1-R5](diffhunk://#diff-2dd8b30c2f33e6503c9b5ea2adda3afa3549e6aeb1f9ca690407fc5b0f7740b6R1-R5))
* …
> [TBCCT-25|29|30] adds forgot-password pages

- api/src/modules/auth/strategies/email-update.strategy.ts
This pull request includes changes to the `email-update.strategy.ts` file to simplify the email confirmation JWT strategy by removing an unused import and modifying the `validate` method to no longer require the `Request` parameter.
Codebase simplification:
* [`api/src/modules/auth/strategies/email-update.strategy.ts`](diffhunk://#diff-dd7a0c2681c252012e4b6c4a5407387cf7188ece7d0cc20c29b6673bd41c64fcL7): Removed the unused import of `Request` from 'express'.
* [`api/src/modules/auth/strategies/email-update.strategy.ts`](diffhunk://#diff-dd7a0c2681c252012e4b6c4a5407387cf7188ece7d0cc20c29b6673bd41c64fcL31-R30): Modified the `validate` method to no longer require the `Request` parameter.
> fix bug missing id in payload

- client/package.json
- client/src/app/(projects)/page.tsx
- client/src/components/ui/resizable.tsx
- client/src/containers/projects/table-visualization/data-table/index.tsx
- client/src/containers/projects/table-visualization/index.tsx
- client/src/containers/projects/table-visualization/toolbar/info-download/index.tsx
- pnpm-lock.yaml
This pull request introduces a new resizable panel feature to the project pages and includes several dependency updates. The most important changes are the addition of the `react-resizable-panels` library and the integration of resizable panels in the project pages.
* **Integration of `react-resizable-panels` library**:
* Added `react-resizable-panels` to `client/package.json` and `pnpm-lock.yaml` for implementing resizable panels. (`client/package.json` [[1]](diffhunk://#diff-1846122c2c83a486a3693f7966aa522c34cf489f674185c4da0d9221683fd81fR41) `pnpm-lock.yaml` [[2]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR363-R365) [[3]](diffhunk://#diff-32824c984905bb02bc7ffcef96a77addd1f1602cff71a11fbbfdd7f53ee026bbR6711-R6716) …
> [N/A] adds resizeable panels to map and table views

- client/src/app/(overview)/store.ts
- client/src/app/globals.css
- client/src/components/map/index.tsx
- client/src/components/map/popup/index.tsx
- client/src/components/ui/badge.tsx
- client/src/containers/projects/map/index.tsx
- client/src/containers/projects/map/layers/projects/index.tsx
- client/src/containers/projects/map/popup/index.tsx
- client/src/lib/format.tsx
This pull request introduces several new features and improvements to the map functionality in the project. The most important changes include adding a popup feature to the map, enhancing the map's interactive elements, and creating reusable UI components.
* **Map Popup Implementation:**
- Added `popupAtom` to manage the state of the map popup (`client/src/app/(overview)/store.ts`).
- Created `MapPopup` component to display popups on the map (`client/src/components/map/popup/index.tsx`).
- Integrated `CostAbatementPopup` to show detailed information in the popup (`client/src/containers/projects/map/popup/index.tsx`).
- Updated `ProjectsMap` to handle popup state and interactions (`client/src/containers/projects/map/index.tsx`). [[1]](diffhunk://#diff-4f4ecba2278893a422feaa8cde9a6d5e64feaf9 …
> [TBCCT-124] adds popup to map

- api/src/modules/custom-projects/dto/create-custom-project-dto.ts
- api/src/modules/custom-projects/dto/project-assumptions.dto.ts
- api/src/modules/custom-projects/dto/project-cost-inputs.dto.ts
- api/test/integration/custom-projects/custom-projects-validations.spec.ts
This pull request includes several updates to the custom projects module, focusing on adding new DTOs for project assumptions and cost inputs, and updating validation logic accordingly.
* [`api/src/modules/custom-projects/dto/create-custom-project-dto.ts`](diffhunk://#diff-80ab8dc1d1e43e551b92f243312e3cbeb27f3107bbc3ad4e21a99aa240e350c9R13-R14): Added `CustomProjectAssumptionsDto` and `CustomProjectCostInputsDto` to the `CreateCustomProjectDto` class and updated validation messages for these new fields. [[1]](diffhunk://#diff-80ab8dc1d1e43e551b92f243312e3cbeb27f3107bbc3ad4e21a99aa240e350c9R13-R14) [[2]](diffhunk://#diff-80ab8dc1d1e43e551b92f243312e3cbeb27f3107bbc3ad4e21a99aa240e350c9L44-R55)
* [`api/src/modules/custom-projects/dto/project-assumptions.dto.ts`](diffhunk://#diff-bb84adbbd48b3 …
> Add assumptions and cost inputs in the DTO

- client/src/app/(overview)/constants.ts
- client/src/app/(overview)/url-store.ts
- client/src/containers/overview/filters/constants.ts
- client/src/containers/overview/filters/index.tsx
This pull request includes various updates to the cost and abatement potential range handling in the project filters, as well as some refactoring for improved code organization. The most important changes include moving constants to a new file, updating the initial state for cost and abatement potential ranges, and adding state management for these ranges in the filters component.
Refactoring and code organization:
* Moved `INITIAL_COST_RANGE` and `INITIAL_ABATEMENT_POTENTIAL_RANGE` constants from `client/src/app/(overview)/constants.ts` to `client/src/containers/overview/filters/constants.ts`. [[1]](diffhunk://#diff-b562766a09a1218eca098ced3a922102da177bd4d747b4432288aece5b7d5069L18-L24) [[2]](diffhunk://#diff-988e384f52c735046b606a201c3da8883ee9896203298f57059a7d50de43b884R15-R19) …
> [TBCCT-107] implements dynamic costs ranges and abatement

- package.json
This pull request includes an update to the `packageManager` version in the `package.json` file. The version has been changed from `pnpm@9.9.0` to `pnpm@9.13.2`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L18-R18): Updated `packageManager` version to `pnpm@9.13.2` to ensure compatibility with the latest features and bug fixes.
> [N/A] pnpm@9.13.2

- client/next.config.mjs
- client/src/app/(overview)/url-store.ts
- client/src/containers/overview/filters/index.tsx
This pull request introduces changes to the `url-store.ts` file to enhance the state management for filters and popups in the overview section of the application. The main updates include the addition of a new state atom and a function to update filters while managing the popup state.
State management improvements:
* [`client/src/app/(overview)/url-store.ts`](diffhunk://#diff-988e384f52c735046b606a201c3da8883ee9896203298f57059a7d50de43b884R11-R16): Added import for `useAtom` from "jotai" and `popupAtom` from the local store.
* [`client/src/app/(overview)/url-store.ts`](diffhunk://#diff-988e384f52c735046b606a201c3da8883ee9896203298f57059a7d50de43b884L51-R68): Modified `useGlobalFilters` to include `popup` state management with `useAtom`, and added an `updateFilters` function to handle …
> Bugfix closing map popup after selecting filter

- api/src/modules/notifications/email/templates/welcome-email.template.ts
fixed typo in signup email text
> fix: typo in signup email text

- client/src/containers/my-projects/columns.tsx
- client/src/containers/nav/index.tsx
- client/src/containers/overview/map/popup/index.tsx
- client/src/containers/overview/table/view/overview/columns.tsx
This PR includes below tasks -
TBCCT-183 - Hide "update selection" button in my custom projects table
TBCCT-187 - Hide Methodology tab in navigation sidebar
TBCCT-193 - Text changes in exchange unit order in map tooltips
TBCCT-192 - change cost columns title and its values
> Text changes and hiding elements temporarily

- client/src/containers/my-projects/columns.tsx
[TBCCT-184](https://vizzuality.atlassian.net/browse/TBCCT-184)
[TBCCT-184]: https://vizzuality.atlassian.net/browse/TBCCT-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE]: Add route to navigate to custom project detail from my project list

- client/src/components/ui/dialog.tsx
- client/src/constants/tooltip.tsx
- client/src/containers/overview/header/parameters/index.tsx
[TBCCT-197](https://vizzuality.atlassian.net/browse/TBCCT-197)
[TBCCT-197]: https://vizzuality.atlassian.net/browse/TBCCT-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE]: Add info button for "project size", "carbon pricing type" and "cost" filters 

- client/src/containers/overview/table/toolbar/index.tsx
This pull request includes several changes to the `ToolbarProjectsTable` component in `client/src/containers/overview/table/toolbar/index.tsx` to improve the user interface and readability. The most important changes include adding new text elements, modifying existing CSS classes, and restructuring the layout for better presentation.
Improvements to user interface and readability:
* Added a new text element "Table details" to the toolbar for better context.
* Modified the `TabsContent` class to reduce spacing between elements, enhancing the compactness of the layout.
* Added a new paragraph explaining the abatement potential and cost metrics to provide more detailed information.
* Removed unnecessary margin from a `div` element to streamline the layout.
Restructuring and layout …
> [TBCCT-199] adds tooltip description and minor styling issues

- client/src/app/layout.tsx
This pull request includes a change to the metadata in the `client/src/app/layout.tsx` file. The title and description of the metadata have been updated to provide a more detailed and accurate representation of the Blue Carbon Cost Tool.
Metadata update:
* [`client/src/app/layout.tsx`](diffhunk://#diff-534df09572a415c8de5c39cdc4a3f923f9e4ea042e2536ffa5e18b01118bdaecL26-R28): Updated the `title` to "Blue Carbon Cost Tool" and provided a comprehensive `description` detailing the purpose and functionality of the tool.
> [TBCCT-174] updates description metadata

- client/src/components/ui/bar-chart/single-stacked-bar-chart/index.tsx
- client/src/containers/my-projects/columns.tsx
- client/src/containers/overview/table/toolbar/index.tsx
- client/src/containers/overview/table/view/overview/columns.tsx
- client/src/containers/overview/table/view/overview/index.tsx
- client/tailwind.config.ts
[TBCCT-179](https://vizzuality.atlassian.net/browse/TBCCT-179)
[TBCCT-179]: https://vizzuality.atlassian.net/browse/TBCCT-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [FE]: Add abatement potencial and total cost chart columns

- client/src/containers/profile/index.tsx
- Add dynamic imports for FileUpload and FileUploadDescription components
- Remove static imports while keeping TEMPLATE_FILES constant
- Optimize bundle size by lazy loading components based on feature flags
> feat: implement dynamic imports for FileUpload components

- client/src/app/providers.tsx
- client/src/components/session-checker/index.tsx
- client/src/lib/query-keys.ts
- client/src/lib/utils.ts
- client/src/middleware.ts
- Added new `SessionChecker` component to monitor authentication state
- Extracted private path validation logic from middleware to utils for reusability
- Added `validateToken` query key for auth operations
- Refactored middleware to use the extracted `isPrivatePath` utility function
- Integrated `SessionChecker` component within the app's provider hierarchy
- Created `isPrivatePath` utility function using the existing private pages regex pattern
- Updated middleware to use the new utility function for consistency
- Added token validation support in query keys
> Session Management and Auth Path Validation Bugfix

- client/src/app/layout.tsx
- client/src/containers/my-projects/index.tsx
- client/src/containers/overview/filters/index.tsx
- client/src/containers/overview/index.tsx
- client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
- client/src/containers/profile/index.tsx
- client/src/containers/projects/custom-project/index.tsx
- client/src/containers/projects/new/index.tsx
- 🎨 Standardized horizontal spacing to `mx-4` across main containers
- 📜 Added scrolling capability to filters sidebar
- 🔄 Replaced `Table` with `ScrollableTable` in scorecard view
- Removed redundant margin from root layout
- Added `ScrollArea` component to filters sidebar for better overflow handling
- [TBCCT-207](https://vizzuality.atlassian.net/browse/TBCCT-207)
- [TBCCT-227](https://vizzuality.atlassian.net/browse/TBCCT-227)
[TBCCT-207]: https://vizzuality.atlassian.net/browse/TBCCT-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-227]: https://vizzuality.atlassian.net/browse/TBCCT-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: UI space and scrolling problems

- client/src/containers/overview/filters/index.tsx
- client/src/containers/projects/form/setup/constants.ts
- client/src/containers/projects/form/setup/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-233)
> fix: update content

- client/src/containers/auth/signup/form/index.tsx
- client/src/containers/projects/new/sidebar.tsx
- client/src/lib/constants.ts
- Added clickable links to Privacy Policy and Terms & Conditions in the signup form
- Added Privacy Policy link in the project creation sidebar
- Imported privacy policy and terms & conditions URLs from constants
[TBCCT-154](https://vizzuality.atlassian.net/browse/TBCCT-154)
[TBCCT-154]: https://vizzuality.atlassian.net/browse/TBCCT-154?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FE - Link terms and conditions & privacy policy

- client/.env.development
- client/src/containers/profile/file-upload/index.tsx
- client/src/hooks/use-feature-flags.ts
This PR introduces two main changes:
1. **Environment Variables & Feature Flags**
- Added new environment variable:
- `NEXT_PUBLIC_FEATURE_FLAGS`: Enables dynamic feature flag configuration
- Implemented dynamic feature flags system:
- Replaced static feature flags with environment-based configuration
- Added TypeScript interface for better type safety
- Uses `useMemo` for performance optimization
- Supports comma-separated list of flags
2. **File Upload Terms & Conditions**
- Added consent notice to file upload component
- Integrated Terms & Conditions link
- Improved user transparency regarding data sharing
Feature flags can be enabled by setting `NEXT_PUBLIC_FEATURE_FLAGS` in your `.env` file:
```
NEXT_PUBLIC_FEATURE_FLAGS=edit-project,share-information,project-comparison
```
Available …
> feat: added T&C consent to file upload and refactor feature flags

- client/src/components/ui/currency.tsx
- client/src/components/ui/graph.tsx
- client/src/containers/intro-modal/index.tsx
- client/src/containers/intro-modal/utils.ts
- client/src/containers/overview/map/popup/index.tsx
- client/src/containers/overview/table/view/overview/columns.tsx
- client/src/lib/format.tsx
- client/src/lib/utils.ts
- Refactors currency formatting to use the Currency component consistently across the application
- Improves code organization by moving intro modal related code to a dedicated utils file
- Fixes CO2 typography in table headers to use correct capitalization (tCO2e)
- Improves map popup formatting and clarifies text for project combinations
[TBCCT-245](https://vizzuality.atlassian.net/browse/TBCCT-245)
[TBCCT-245]: https://vizzuality.atlassian.net/browse/TBCCT-245?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: currency component and intro modal organization

- client/src/constants/tooltip.tsx
- client/src/containers/overview/project-details/left-over/index.tsx
- client/src/containers/projects/custom-project/left-over/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-269)
> refactor: rename leftover after OPEX to net revenue after OPEX/total cost

- client/src/containers/overview/table/view/key-costs/index.tsx
- client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
- client/src/lib/format.tsx
- Added padding to table headers for better spacing
- Enhanced number formatting to remove trailing ".00" for cleaner display
> fix: formatting + spacing table header

- client/src/components/ui/score-card.tsx
- client/src/containers/overview/table/utils.tsx
- client/src/containers/overview/table/view/key-costs/columns.tsx
- client/src/containers/overview/table/view/key-costs/constants.ts
- client/src/containers/overview/table/view/key-costs/index.tsx
- client/src/containers/overview/table/view/overview/columns.tsx
- client/src/containers/overview/table/view/overview/index.tsx
- client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
This pull request includes several changes to the table components in the `client/src/containers/overview/table` directory, focusing on refactoring and enhancing the key costs table. The changes involve renaming files, adding utility components, and updating the table structure and functionality.
* **File Renaming and Imports:**
- Renamed `client/src/containers/overview/table/utils.ts` to `utils.tsx` and updated imports to include `PropsWithChildren`.
* **Utility Components:**
- Added `HeaderText` and `CellText` components to `utils.tsx` for consistent styling of table headers and cells.
* **Key Costs Table Columns:**
- Removed commented-out code and added dynamic column definitions in `columns.tsx` for the key costs table, including the use of `HeaderText` and `CellText` components for …
> [TBCCT-266] fetches keycosts

- api/src/modules/import/import.service.ts
This pull request includes changes to the `ImportService` class in the `api/src/modules/import/import.service.ts` file to add event handling and logging to the `importDataProvidedByPartner` method. The most important changes include adding log messages and registering import events at different stages of the import process.
Event handling and logging improvements:
* Added a warning log message at the start of the `importDataProvidedByPartner` method and registered the import start event.
* Added a warning log message upon successful completion of the `importDataProvidedByPartner` method and registered the import success event.
* Added error handling with an error log message and registered the import failure event, throwing a `ConflictException` in case of an error.
> [TBCCT-159] feat(api): Refactor importDataProvidedByPartner and add event logs

- backoffice/.prettierrc
- backoffice/components/pages/file-ingestion/page.tsx
- backoffice/index.ts
- Reordered tabs to match the required upload sequence (Scorecards first, then Data)
- Added instructions about the required upload order
- Updated tab labels and state management to be more descriptive ("scorecard" and "data" instead of "first" and "second")
- Simplified the upload button to just show "Send" instead of an icon
- Improved error messaging to be more specific about which file is missing
- Centered the upload button for better visual alignment
- Added .prettierrc for consistent code formatting
[TBCCT-254](https://vizzuality.atlassian.net/browse/TBCCT-254)
Verify:
1. Scorecard file upload works in the first tab
2. Data file upload works in the second tab
3. Error messages display correctly when files are missing
4. Success messages show after successful uploads
[TBCCT-254]: …
> refactor: improved file-ingestion upload flow and UX

- api/src/modules/custom-projects/custom-projects.controller.ts
- api/src/modules/custom-projects/custom-projects.service.ts
- client/src/containers/projects/custom-project/header/index.tsx
- client/src/hooks/use-get-custom-project.ts
- shared/contracts/custom-projects.contract.ts
- Updates custom project header to display the dynamic project name instead of static text
- Update API to return project ID when saving custom projects
- Update client to use returned ID for proper URL updates
- Fix project preview state handling and query cache priority
> fix: custom-project title

- client/src/containers/projects/custom-project/details/detail-item/index.tsx
- client/src/containers/projects/custom-project/details/index.tsx
- client/src/hooks/use-custom-project-output.ts
This PR fixes the handling of loss rate & emission factors custom project preview page.
- Add explicit null handling for `value` prop in `DetailItem` component
- Update emission factor display logic to show either:
- A single total value, or
- Values of AGB/SOC
- Fix loss rate parsing by converting to percentage value
- [TBCCT-274](https://vizzuality.atlassian.net/browse/TBCCT-274)
[TBCCT-274]: https://vizzuality.atlassian.net/browse/TBCCT-274?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: lossRate and emission factor in preview page

- client/src/components/ui/score-card.tsx
- client/src/containers/overview/table/view/scorecard-prioritization/index.tsx
Fixes issue with background color, see [Jira](https://vizzuality.atlassian.net/browse/TBCCT-223)
> fix: scorecard cells background color

- client/src/containers/projects/form/setup/conservation-project-details/index.tsx
- client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-306)
> feat: Update form labels + enhance form accessibility

- api/src/modules/import/import.repostiory.ts
- api/test/integration/methodology/model-component-sources.spec.ts
- backoffice/components/atoms/selector.type.tsx
- backoffice/components/index.tsx
- backoffice/components/molecules/emission-factors-sources.tsx
- backoffice/components/molecules/many-2-many-sources.tsx
- backoffice/datasource.ts
- backoffice/index.ts
- backoffice/resources/common/common.resources.ts
- backoffice/resources/common/many-2-many-sources.actions.ts
- backoffice/resources/countries/country.resource.ts
- backoffice/resources/emission-factors/emission-factors.resource.ts
- backoffice/resources/model-component-source/emissions-factors-source.resource.ts
- backoffice/resources/model-component-source/model-component-source.resource.ts
- backoffice/resources/project-size/project-size.resource.ts
- pnpm-lock.yaml
- shared/entities/base-data.view.ts
- shared/entities/carbon-inputs/emission-factors.entity.ts
- shared/entities/cost-inputs/project-size.entity.ts
- shared/entities/methodology/emission-factor-source.entity.ts
- shared/entities/methodology/emission-factor.type.ts
- shared/entities/methodology/model-component-source.entity.ts
- shared/lib/db-entities.ts
This pull request introduces several changes across multiple files to enhance the functionality of the import repository, add new tests, and improve the backoffice components. The most important changes include the addition of a new entity, updates to the import repository, and the creation of new integration tests.
* Added `ModelComponentSource` to the import repository (`api/src/modules/import/import.repostiory.ts`).
* Modified the transaction handling in the `ImportRepository` to include `ModelComponentSource` and improved error handling. [[1]](diffhunk://#diff-a7f7a9963ea5c5c2c3ea37d5ac6e435be607b406814aa09d2811ff7163019358L75-R77) [[2]](diffhunk://#diff-a7f7a9963ea5c5c2c3ea37d5ac6e435be607b406814aa09d2811ff7163019358L102-R110) …
> feat: TBCCT-300 BE - Update datamodel to add the Sources Entities

- api/src/modules/calculations/cost.calculator.ts
- api/src/modules/calculations/sequestration-rate.calculator.ts
- api/src/modules/custom-projects/dto/create-custom-project.dto.ts
- api/src/modules/custom-projects/dto/restoration-project-params.dto.ts
- api/src/modules/custom-projects/input-factory/custom-project.factory.ts
- api/src/modules/custom-projects/input-factory/restoration-project.input.ts
- api/test/integration/calculations/calculations-restoration.spec.ts
- api/test/integration/custom-projects/custom-projects-create.spec.ts
- shared/entities/base-data.view.ts
This PR fixes blue carbon and community representation cost calculations
Also starts fixing some hardcore issues with typing and missing data around the algorithm
> Tbcct 279 review custom project calculations 2

- client/src/containers/projects/form/setup/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-324)
> fix: default value restorationActivity

- client/src/containers/overview/filters/index.tsx
- client/src/containers/overview/header/parameters/index.tsx
- client/src/containers/projects/custom-project/header/parameters/index.tsx
- client/src/containers/projects/form/assumptions/columns.tsx
- client/src/containers/projects/form/cost-inputs-overrides/capex/columns.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-322)
> fix: typos

- client/src/constants/tooltip.tsx
- client/src/containers/projects/custom-project/left-over/index.tsx
- client/src/hooks/use-custom-project-output.ts
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-314)
> feat: update leftover title based on carbonRevenuesToCover

- client/src/containers/intro-modal/utils.ts
- client/src/containers/nav/index.tsx
- client/src/containers/projects/custom-project/cost/index.tsx
- client/src/containers/projects/custom-project/left-over/index.tsx
- client/src/containers/projects/form/constants.ts
- client/src/containers/projects/form/utils.ts
[TBCCT-325](https://vizzuality.atlassian.net/browse/TBCCT-325)
[TBCCT-325]: https://vizzuality.atlassian.net/browse/TBCCT-325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: typo + alignment graphs

- api/src/modules/calculations/calculation.engine.ts
- api/src/modules/custom-projects/input-factory/custom-project.factory.ts
- api/test/integration/calculations/calculations-restoration.spec.ts
- api/test/integration/calculations/fixtures/restoration-mexico-mangroves.ts
- client/src/hooks/use-custom-project-output.ts
- shared/dtos/custom-projects/custom-project-output.dto.ts
- shared/lib/stubs/custom-project.stub.ts
handles project type specific properties
> Tbcct 279 review custom project calculations 5

- api/src/modules/methodology/methodology.repository.ts
This pull request includes changes to the `MethodologyRepository` class in the `api/src/modules/methodology/methodology.repository.ts` file to handle `ModelAssumptions` and economic factors differently in the data retrieval process. The most important changes include importing the `ModelAssumptions` entity, excluding `ModelAssumptions` from the source configurations, and adding specific handling for economic factors in the SQL query.
Changes to handle `ModelAssumptions` and economic factors:
* [`api/src/modules/methodology/methodology.repository.ts`](diffhunk://#diff-92d32f6cd50ecf42229438cfd17545920ce8096be812381d7f96c89f6c3bb603R5): Imported the `ModelAssumptions` entity to be used in the repository.
* [`api/src/modules/methodology/methodology.repository.ts`](diffhunk://#diff-92d32f6cd50 …
> feat(api): Add economic factors to the methodology sources response

- api/src/modules/methodology/methodology.repository.ts
This pull request includes changes to the `api/src/modules/methodology/methodology.repository.ts` file to improve the readability and maintainability of SQL queries.
Changes to improve SQL query readability:
* [`api/src/modules/methodology/methodology.repository.ts`](diffhunk://#diff-92d32f6cd50ecf42229438cfd17545920ce8096be812381d7f96c89f6c3bb603L89-R89): Added an alias `economic_factors` to the subquery for better clarity and understanding of the query structure.
> fix(api): Add economic factors to the methodology sources response

- client/src/containers/projects/form/assumptions/index.tsx
[TBCCT-332](https://vizzuality.atlassian.net/browse/TBCCT-332)
[TBCCT-332]: https://vizzuality.atlassian.net/browse/TBCCT-332?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: filter out carbon price from assumptions table

- client/src/components/ui/currency.tsx
- client/src/components/ui/graph.tsx
- client/tests/components/ui/graph.test.tsx
- Improved handling of negative values with proper minus sign placement
- Added support for negative leftover values visualization
- [TBCCT-340](https://vizzuality.atlassian.net/browse/TBCCT-340)
- [TBCCT-341](https://vizzuality.atlassian.net/browse/TBCCT-341)
- [TBCCT-342](https://vizzuality.atlassian.net/browse/TBCCT-342)
[TBCCT-340]: https://vizzuality.atlassian.net/browse/TBCCT-340?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-341]: https://vizzuality.atlassian.net/browse/TBCCT-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TBCCT-342]: https://vizzuality.atlassian.net/browse/TBCCT-342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix: Currency Component and Graph Visualization

- client/src/containers/projects/form/constants.ts
- client/src/containers/projects/form/header.tsx
- client/src/containers/projects/form/setup/index.tsx
- shared/schemas/custom-projects/create-custom-project.schema.ts
- [TBCCT-336](https://vizzuality.atlassian.net/browse/TBCCT-336)
[TBCCT-336]: https://vizzuality.atlassian.net/browse/TBCCT-336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: remove projectSpecificLossRate from default values

- backoffice/index.ts
- client/src/app/api/backoffice/signout/route.ts
- client/src/app/auth/signin/page.tsx
- client/src/app/auth/signup/page.tsx
- client/src/components/session-checker/index.tsx
- client/src/containers/auth/signin/form/index.tsx
- client/src/containers/profile/delete-account/index.tsx
- client/src/containers/profile/profile-sidebar/index.tsx
- client/src/lib/constants.ts
- client/src/lib/utils.ts
- e2e/tests/auth/delete-account.spec.ts
- e2e/tests/auth/sign-in.spec.ts
- e2e/tests/auth/update-email.spec.ts
- e2e/tests/auth/update-password.spec.ts
- shared/lib/e2e-test-manager.ts
- Created `REDIRECT_SIGNIN_PATH` constant in `constants.ts` with value of "/"
- Modified the admin login redirect to properly encode the callback URL
- Remove backoffice cookie after signout
[TBCCT-323](https://vizzuality.atlassian.net/browse/TBCCT-323)
[TBCCT-323]: https://vizzuality.atlassian.net/browse/TBCCT-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Update Authentication Redirect Paths

- client/src/containers/projects/custom-project/breakeven-price-modal/index.tsx
- client/src/containers/projects/custom-project/index.tsx
- client/src/containers/projects/form/index.tsx
- client/src/containers/projects/form/utils.ts
- client/tests/projects/form/default-values.test.tsx
- Imported and integrated the `BreakevenPriceModal` component
- Added redirect path logic based on project ID
- Added caching support for form values with a new `useCache` parameter
- [TBCCT-283](https://vizzuality.atlassian.net/browse/TBCCT-283)
[TBCCT-283]: https://vizzuality.atlassian.net/browse/TBCCT-283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: added breakeven-price-modal

- client/src/containers/projects/form/setup/index.tsx
- client/src/containers/projects/form/utils.ts
- client/src/containers/projects/form/utils/parse-form-values.ts
- client/tests/shared/utils.test.ts
- shared/lib/utils.ts
- shared/schemas/custom-projects/create-custom-project.schema.ts
- Moving ValidatedCustomProjectForm type to schema file
- Replacing manual data transformations with utility functions
- Simplifying assumption and cost input processing
- [TBCCT-358](https://vizzuality.atlassian.net/browse/TBCCT-358)
[TBCCT-358]: https://vizzuality.atlassian.net/browse/TBCCT-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor: extract form value parsing logic into shared utils

- backoffice/providers/auth.provider.ts
This pull request includes changes to the `backoffice/providers/auth.provider.ts` file, focusing on code style consistency and security improvements.
* Updated import statements to use single quotes instead of double quotes for consistency.
* Changed string literals within the `handleLogin` method to use single quotes.
* Added the `Secure` attribute to the `__Secure-next-auth.session-token` cookie to ensure it is only sent over HTTPS connections.
>  feat: Allow multiple backoffice sessions for the same user, admin cookies should last the same as the access tokens

- client/src/components/ui/currency.tsx
- client/src/components/ui/graph.tsx
- client/src/containers/projects/form/header.tsx
- client/src/containers/projects/form/setup/conservation-project-details/index.tsx
- client/tests/components/ui/currency.test.tsx
This PR introduces improvements to number formatting, graph displays, and form handling.
- Added compact notation for numbers ≥ 1 trillion in Currency component
- Improved text overflow handling with ellipsis and proper CSS classes
- Improved loss rate form field handling
- Added cleanup of unnecessary projectSpecificLossRate when using national average
- Fixed trigger timing for form validation
- [TBCCT-355](https://vizzuality.atlassian.net/browse/TBCCT-355)
[TBCCT-355]: https://vizzuality.atlassian.net/browse/TBCCT-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: projectSpecificLossRate displaying error message

- client/src/containers/projects/form/assumptions/index.tsx
- client/src/containers/projects/form/number-form-item.tsx
- client/src/containers/projects/form/readonly-input.tsx
- client/src/containers/projects/form/setup/conservation-project-details/index.tsx
- client/src/containers/projects/form/setup/conservation-project-details/loss-rate.tsx
- client/src/containers/projects/form/setup/conservation-project-details/t1-global-emission-factor.tsx
- client/src/containers/projects/form/setup/conservation-project-details/t2-national-emission-factors.tsx
- client/src/containers/projects/form/setup/index.tsx
- client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
- client/src/containers/projects/form/table/index.tsx
- e2e/constants/index.ts
- e2e/package.json
- e2e/tests/auth/delete-account.spec.ts
- e2e/tests/auth/sign-in.spec.ts
- e2e/tests/auth/sign-up.spec.ts
- e2e/tests/auth/update-email.spec.ts
- e2e/tests/auth/update-password.spec.ts
- e2e/tests/custom-projects/create-custom-project.spec.ts
- pnpm-lock.yaml
- shared/lib/e2e-test-manager.ts
- shared/schemas/custom-projects/create-custom-project.schema.ts
- Added E2E testing infrastructure and constants
- Created test user constants and route definitions
- Added watch mode for E2E tests using concurrently
- Refactored E2E tests to use centralized constants
- Form Component Improvements
- Created new `ReadonlyInput` component to reduce code duplication
- Added data-testid attributes to form elements for better testing
- Improved number formatting in readonly fields
- Added table ID support for assumptions table
- Added E2E test infrastructure with proper configuration
- Improved testability by adding data-testid attributes
- Added watch mode for better development experience
- [TBCCT-354](https://vizzuality.atlassian.net/browse/TBCCT-354)
[TBCCT-354]: https://vizzuality.atlassian.net/browse/TBCCT-354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
> Tbcct 354 add tests for create custom project form for most critical use cases

- api/src/modules/calculations/data.repository.ts
- api/src/modules/projects/projects.service.ts
- backoffice/resources/projects/project.actions.ts
This pull request includes several changes to the `api/src/modules` and `backoffice/resources/projects` files to improve functionality and error handling. The most important changes include adding new logic for project creation, modifying query conditions, and refining error handling in the `beforeHook` function.
* [`api/src/modules/projects/projects.service.ts`](diffhunk://#diff-f4e9fe665933514d01aa02820eac87bc916dc468d4f5cb3e4ad50901c441417aL225-R246): Enhanced the project creation process by integrating additional data such as `scoreCardRating`, `costs`, and `projectSize` before saving the project.
* [`api/src/modules/calculations/data.repository.ts`](diffhunk://#diff-c610941a76971fae93d7d206fcbe042270836b452cabbd2d24eb844e96cfdc2eR310-R316): Added a check to ensure …
> fix: Fix project creation from the back office

- api/src/modules/config/app-config.service.ts
- api/src/modules/config/env-config.schema.ts
- api/src/modules/import/s3.service.ts
- api/test/utils/mocks/test-import.service.ts
This pull request introduces several significant changes across multiple files to enhance the functionality and integration of S3 services, improve file handling, and modify configurations in the API module. The most important changes include the addition of S3 service integration, updates to the import controller, modifications to the configuration files, and new scripts in the package.json file.
* Added `S3Service` to handle S3 operations such as file uploads, downloads, and bucket management. (`api/src/modules/import/s3.service.ts`)
* Updated `ImportService` to use `S3Service` for uploading and downloading user files. (`api/src/modules/import/import.service.ts`) [[1]](diffhunk://#diff-695dbebee9d4a7e0e05fd8c18fa8c56c5526003239ff604eb4b8931839c329b8L12-R25) …
> test(api): Implement missing methods in the test-import.service so we can properly test user uploads feature

- api/package.json
- api/src/modules/import/import.controller.ts
- api/src/modules/import/import.service.ts
- api/src/modules/import/s3.service.ts
- api/src/modules/import/utils/s3.utils.ts
- api/test/integration/import/user-uploads.spec.ts
- api/test/utils/mocks/test-import.service.ts
- backoffice/resources/common.actions.ts
- backoffice/resources/projects/project.actions.ts
- backoffice/resources/projects/projects.resource.ts
- backoffice/resources/users/user-upload.actions.ts
- backoffice/resources/users/user-upload.resource.ts
- backoffice/resources/users/user.actions.ts
- docker-compose.test.yml
- shared/contracts/users.contract.ts
This pull request introduces several updates to enhance file upload management, improve S3 operations, and streamline backoffice functionality. Key changes include adding a feature to delete user-uploaded data, improving S3 key generation, and refactoring backoffice actions for better code reuse and clarity.
* Added a new endpoint `deleteUploadedData` to the `usersContract` for deleting user-uploaded data, including the corresponding controller and service logic to handle S3 file deletion and database cleanup. (`[[1]](diffhunk://#diff-9aa2731a3c9ddbbe326ef0bf2dc4d7584fcadd538036381ce548eede4b2f1a9dR71-R77)`, `[[2]](diffhunk://#diff-4ed2660ea42131107f248d52bde409186e43eb3b926b389ecba3f34cd67553fdR124-R137)`, `[[3]](diffhunk://#diff-695dbebee9d4a7e0e05fd8c18fa8c56c5526003239ff604eb4b8931839c …
> feat: Allow admins to clean up user-uploads to free up space in the s3 bucket

- api/src/modules/auth/guards/jwt-cookie-auth.guard.ts
- api/src/modules/import/import.controller.ts
- client/src/containers/profile/file-upload/description/index.tsx
- client/src/containers/profile/file-upload/index.tsx
- client/src/containers/profile/index.tsx
- client/src/lib/feature-flags.ts
- client/src/lib/query-keys.ts
- shared/contracts/users.contract.ts
- shared/dtos/users/upload-data-files.constants.ts
- shared/dtos/users/upload-data-files.dto.ts
- Enabled "Share Information" feature flag
- Refactored file upload system to support dynamic templates and file types
- Added support for multiple file extensions (.pdf, .xlsm, .xlsx, .xlm)
- Added unique file naming to prevent duplicates
- [TBCCT-386](https://vizzuality.atlassian.net/browse/TBCCT-386)
[TBCCT-386]: https://vizzuality.atlassian.net/browse/TBCCT-386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(client): enable share-information in frontend

- client/src/containers/projects/form/setup/conservation-project-details/index.tsx
- client/src/containers/projects/form/setup/index.tsx
[Jira](https://vizzuality.atlassian.net/browse/TBCCT-383?focusedCommentId=35451)
> feat(client): disable invalid emissionFactorUsed options

- backoffice/components/pages/file-ingestion/page.tsx
This pull request contains changes to the `backoffice/components/pages/file-ingestion/page.tsx` file, focusing on improving file upload handling. The updates include fixing a logical condition and adding a new state update for scorecard file uploads.
* Corrected a logical condition in the `UploadTab` component by replacing `isUploading == false` with `false == false`, likely as a temporary placeholder or debugging step.
* Added a call to `setScoreCardFile` in the `handleFileUpload` function to update the state when a scorecard file is uploaded. This ensures the file is properly tracked in the application state.
> fix(back-office): Fix UI file upload form

- backoffice/components/molecules/many-2-many-sources.tsx
> fix(backoffice): overflow sources items

- client/src/components/ui/bar-chart/single-stacked-bar-chart/index.tsx
- client/src/containers/overview/table/utils.tsx
- client/src/containers/projects/custom-project/cost-details/index.tsx
- client/src/containers/projects/custom-project/cost-details/table/columns.tsx
- client/src/containers/projects/custom-project/cost-details/table/index.tsx
- client/src/containers/projects/custom-project/cost-details/table/sensitivity-analysis/index.tsx
- client/src/hooks/use-custom-project-output.ts
- shared/dtos/custom-projects/custom-project-output.dto.ts
Task: https://vizzuality.atlassian.net/browse/TBCCT-385
This pull request introduces enhancements to the cost details table for custom projects, focusing on adding sensitivity analysis data and improving component flexibility. Key changes include the addition of a new `SensitivityAnalysisColumn` component, updates to data types and structures, and adjustments to existing components for better scalability and maintainability.
* **Added `SensitivityAnalysisColumn` Component**: Introduced a new component to display sensitivity analysis data visually, including scaled negative and positive values. This component uses a bar chart-like visualization to represent percentage changes. (`[client/src/containers/projects/custom-project/cost-details/table/sensitivity-analysis/index.tsxR1-R53](diffhunk: …
> [TBCCT-385] implements sensitivity analysis

- client/src/containers/projects/form/setup/activity/index.tsx
- e2e/tests/custom-projects/edit-custom-project.spec.ts
- shared/schemas/custom-projects/custom-project-form.constants.ts
- [TBCCT-387](https://vizzuality.atlassian.net/browse/TBCCT-387)
[TBCCT-387]: https://vizzuality.atlassian.net/browse/TBCCT-387?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(client): get plantingSuccessRate from api

- api/src/modules/custom-projects/input-factory/restoration-project.input.ts
- api/test/integration/custom-projects/custom-projects-validations.spec.ts
- client/src/containers/projects/form/header.tsx
- client/src/containers/projects/form/utils/parse-form-values.ts
- client/tests/shared/transform-create-custom-project-payload.test.ts
- shared/lib/transform-create-custom-project-payload.ts
- shared/schemas/custom-projects/create-custom-project.schema.ts
Task: https://vizzuality.atlassian.net/browse/TBCCT-415
This pull request introduces significant changes to the handling of restoration project data, focusing on replacing the `restorationYearlyBreakdown` concept with a new `customRestorationPlan` schema. These changes improve validation, data transformation, and consistency between the client and API. Additionally, the pull request includes updates to the front-end form handling, utility functions, and related tests to align with the new schema.
* Replaced `restorationYearlyBreakdown` with `customRestorationPlan` in the `RestorationCustomProjectSchema` and introduced `RestorationPlanDTOSchema` for consistent validation of restoration plans. [[1]](diffhunk://#diff-e2acc2e0e44826a98602752f24e3062f9cfd0526a60190ad2f8b02d0127fdbf0L61-R56) …
> [TBCCT-415] splits and validates restoration plan schemas

- client/src/components/ui/info-button.tsx
- client/src/containers/projects/custom-project/cost-details/index.tsx
Task: https://vizzuality.atlassian.net/browse/TBCCT-407
This pull request introduces improvements to the `InfoButton` component and refines its usage in the cost details section. The changes enhance the component's styling and functionality, making it more reusable and consistent across the application.
* **Reorganized imports**: Adjusted the order of imports for better readability and added imports for utility and UI components, including `cn` from `@/lib/utils` and `ScrollArea` from `@/components/ui/scroll-area`. [[1]](diffhunk://#diff-dc22e6c244cd47a6cc22cf2c19040054c40d2fccdf9520e6364175e9cc367d62L1-R2) [[2]](diffhunk://#diff-dc22e6c244cd47a6cc22cf2c19040054c40d2fccdf9520e6364175e9cc367d62R15-R16)
* **Enhanced styling and layout**: Updated the `DialogContent` to include additional …
> [TBCCT-407] adds scroll in dialogs by default

- client/src/components/ui/graph.tsx
- client/src/components/ui/sheet.tsx
- client/src/containers/projects/custom-project/index.tsx
- client/src/containers/projects/custom-project/summary/index.tsx
- e2e/tests/custom-projects/edit-custom-project.spec.ts
Task: https://vizzuality.atlassian.net/browse/TBCCT-418
https://github.com/user-attachments/assets/7e19be84-10fd-4e71-bcd1-28e32b1462ac
This pull request introduces several updates to improve UI components, refactor code, and simplify state management in the `CustomProject` and related components. The most significant changes include replacing `motion` with `Sheet` for the project summary sidebar, simplifying imports and state management, and updating UI styles for consistency.
* Replaced `motion` with `Sheet` for the project summary sidebar in `CustomProjectView`, simplifying the layout and adding a consistent UI for the sidebar. The `Sheet` component now handles the open/close state and styling of the sidebar (`client/src/containers/projects/custom-project/index.tsx`, …
> [TBCCT-418] moves project summary to sheet to improve page responsiveness

- client/src/constants/tooltip.tsx
- client/src/containers/methodology/sections/carbon-emissions-reductions-and-carbon-credit-revenues/index.tsx
- client/src/containers/methodology/sections/introduction/index.tsx
- client/src/containers/methodology/sections/limitations-of-the-tool/index.tsx
- client/src/containers/methodology/sections/model-assumptions/index.tsx
- client/src/containers/methodology/sections/project-costs-assumptions-and-methodology/index.tsx
- client/src/containers/methodology/sections/project-size-assumptions/index.tsx
- client/src/containers/methodology/sections/qualitative-scorecard-details-and-sources/index.tsx
- shared/schemas/assumptions/assumptions.enums.ts
Task: https://vizzuality.atlassian.net/browse/TBCCT-414
This pull request includes updates to the methodology and assumptions for the Blue Carbon Cost Tool, focusing on simplifying and clarifying content, removing redundant details, and improving customization options. The changes span multiple sections, including tooltips, methodology sections, and assumptions.
* Simplified the explanation of the `DISCOUNT_RATE` tooltip to focus on user customization for restoration rates. (`client/src/constants/tooltip.tsx`, [client/src/constants/tooltip.tsxL626-R627](diffhunk://#diff-2b744b2243d43bdf923aa2dfd80e6e554c62b35ccc781c08ea14f29f5d737e4dL626-R627))
* Streamlined the `BUFFER` tooltip by removing detailed descriptions of non-permanence, leakage, and uncertainty, consolidating the explanation …
> [TBCCT-414] updates methodology content with May updates

- client/src/containers/methodology/index.tsx
Task: https://vizzuality.atlassian.net/browse/TBCCT-411
> [TBCCT-411] methodology scroll spy: reduces negative bottom margin

- client/src/components/ui/list.tsx
- client/src/constants/tooltip.tsx
- client/src/containers/overview/filters/index.tsx
- client/src/containers/overview/header/parameters/index.tsx
- client/src/containers/overview/table/toolbar/index.tsx
- client/src/containers/projects/custom-project/header/parameters/index.tsx
- client/src/containers/projects/form/cost-inputs-overrides/index.tsx
- client/src/containers/projects/form/restoration-plan/index.tsx
- client/src/containers/projects/form/setup/index.tsx
- client/src/containers/projects/form/setup/restoration-project-detail/index.tsx
- shared/schemas/assumptions/assumptions.enums.ts
Task: https://vizzuality.atlassian.net/browse/TBCCT-408
> [TBCCT-408] updates tooltips content

- client/src/components/ui/info-button.tsx
- client/src/containers/projects/form/cost-inputs-overrides/index.tsx
- client/src/containers/projects/form/restoration-plan/index.tsx
This pull request refactors the `InfoButton` component to improve its flexibility and updates its usage in two project forms. The most significant changes include replacing the `Button` component with a `div` styled using `buttonVariants`, managing the dialog state directly within `InfoButton`, and integrating the updated component into the `CostInputsOverridesProjectForm` and `RestorationPlanProjectForm`.
* Replaced the `Button` component with a `div` styled using `buttonVariants` to allow more customization and flexibility. [[1]](diffhunk://#diff-dc22e6c244cd47a6cc22cf2c19040054c40d2fccdf9520e6364175e9cc367d62L2-R8) [[2]](diffhunk://#diff-dc22e6c244cd47a6cc22cf2c19040054c40d2fccdf9520e6364175e9cc367d62R27-R47)
* Added local state management (`useState`) to control the dialog's open …
> [N/A] fixes an issue where inner button will trigger the accordion on click

- client/src/containers/projects/custom-project/summary/index.tsx
This pull request introduces a minor improvement to the layout and styling of the `ProjectSummary` component in `client/src/containers/projects/custom-project/summary/index.tsx`. The changes enhance the visual presentation by addressing overflow and adding padding to the scrollable area.
Styling and layout adjustments:
* [`client/src/containers/projects/custom-project/summary/index.tsx`](diffhunk://#diff-8e23072fb98e7dfd759f78dfb8e73d2dcf4c390b500275305b829cedff36541bL52-R57): Added `overflow-hidden` to the main container to prevent content overflow and updated the `ScrollArea` component to include right padding (`pr-4`) for better spacing.
> [TBCCT-455] custom project summary: fixes overflow

- client/src/components/ui/graph.tsx
- client/src/containers/projects/custom-project/cost/index.tsx
- client/src/containers/projects/custom-project/left-over/index.tsx
This pull request refines the layout and styling of several UI components to improve consistency and visual alignment. The changes primarily focus on adjusting spacing, alignment, and layout structures for `Graph`, `GraphWithLegend`, `ProjectCost`, and `LeftOver` components.
* **Graph component (`graph.tsx`)**: Modified the container height and alignment by replacing `min-h-[150px]` with a fixed height of `h-40` and adjusted the `absolute` positioning to include both `bottom-0` and `top-0`.
* **GraphWithLegend component (`graph.tsx`)**: Simplified the structure by introducing a `flex-col` layout with reduced gaps and better alignment for the graph and legend. Removed redundant nested containers and improved the placement of the `Currency` component. …
> [TBCCT-443] better fitting for costs

- api/src/modules/calculations/calculators/sequestration-rate-abatement-potential.calculator.ts
- api/src/modules/custom-projects/input-factory/conservation-project.input.ts
- api/src/modules/custom-projects/input-factory/restoration-project.input.ts
- api/src/modules/import/services/entity.preprocessor.ts
- api/src/modules/projects/projects.service.ts
This pull request introduces several changes to improve code clarity, functionality, and robustness across multiple modules. Key updates include stricter null checks, enhanced fallback logic, method replacements for better type handling, and filtering logic for project processing.
- **Null checks for emission factors**: Updated the null checks in `SequestrationRateCalculatorAbatementPotential` to use `!= null` instead of relying on implicit falsy checks for better clarity and type safety (`api/src/modules/calculations/calculators/sequestration-rate-abatement-potential.calculator.ts`).
- **Method replacement for type handling**: Replaced `stringToNumeric` with `stringToNumberOrNull` in `EntityPreprocessor` to handle null values explicitly when parsing emission factors …
> Calculations fixes

- client/src/containers/projects/form/sidebar.tsx
This pull request updates the `ProjectSidebar` component to improve its layout and usability, particularly for the sidebar's informational section. The main changes are the introduction of a scrollable area for the info card, minor layout adjustments, and cleanup of imports.
**UI/UX Improvements:**
* Wrapped the sidebar's informational card content in a `ScrollArea` component and added `overflow-hidden` to the card, allowing long content to be scrollable and preventing layout overflow. [[1]](diffhunk://#diff-956c7c1c7774ad6300270144c74209229ef20c44c9ffb284b74cdb31ee2f3e79R19) [[2]](diffhunk://#diff-956c7c1c7774ad6300270144c74209229ef20c44c9ffb284b74cdb31ee2f3e79L80-R83) [[3]](diffhunk://#diff-956c7c1c7774ad6300270144c74209229ef20c44c9ffb284b74cdb31ee2f3e79R124)
* Added a `gap-6` class to …
> [N/A] adds overflow to custom project explanation
